// This file has been generated.
export const AccentColor = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const AlignContent = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Center: "center",
    Start: "start",
    End: "end",
    FlexStart: "flex-start",
    FlexEnd: "flex-end",
    Normal: "normal",
    Baseline: "baseline",
    FirstBaseline: "first baseline",
    LastBaseline: "last baseline",
    SpaceBetween: "space-between",
    SpaceAround: "space-around",
    SpaceEvenly: "space-evenly",
    Stretch: "stretch",
    SafeCenter: "safe center",
    UnsafeCenter: "unsafe center",
};
export const AlignItems = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Center: "center",
    Start: "start",
    End: "end",
    FlexStart: "flex-start",
    FlexEnd: "flex-end",
    Normal: "normal",
    Baseline: "baseline",
    FirstBaseline: "first baseline",
    LastBaseline: "last baseline",
    Stretch: "stretch",
    SafeCenter: "safe center",
    UnsafeCenter: "unsafe center",
};
export const AlignSelf = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Center: "center",
    Start: "start",
    End: "end",
    FlexStart: "flex-start",
    FlexEnd: "flex-end",
    Normal: "normal",
    Baseline: "baseline",
    FirstBaseline: "first baseline",
    LastBaseline: "last baseline",
    SpaceBetween: "space-between",
    SpaceAround: "space-around",
    SpaceEvenly: "space-evenly",
    SelfStart: "self-start",
    SelfEnd: "self-end",
    Stretch: "stretch",
    SafeCenter: "safe center",
    UnsafeCenter: "unsafe center",
};
export const AlignTracks = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Start: "start",
    SpaceBetween: "space-between",
    Center: "center",
};
export const AnimationDelay = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
};
export const AnimationFillMode = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Forwards: "forwards",
    Backwards: "backwards",
    Both: "both",
};
export const AnimationIterationCount = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Infinite: "infinite",
};
export const AnimationPlayState = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Running: "running",
    Paused: "paused",
};
export const AnimationTimingFunction = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Ease: "ease",
    EaseIn: "ease-in",
    EaseOut: "ease-out",
    EaseInOut: "ease-in-out",
    Linear: "linear",
    StepStart: "step-start",
    StepEnd: "step-end",
};
export const Appearance = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Auto: "auto",
    MenulistButton: "menulist-button",
    Textfield: "textfield",
    Button: "button",
    Searchfield: "searchfield",
    Textarea: "textarea",
    PushButton: "push-button",
    SlideHorizontal: "slide-horizontal",
    Checkbox: "checkbox",
    Radio: "radio",
    SquareButton: "square-button",
    Menulist: "menulist",
    Meter: "meter",
    ProgressBar: "progress-bar",
};
export const AspectRatio = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const BackdropFilter = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const BackfaceVisibility = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Hidden: "hidden",
    Visible: "visible",
};
export const BackgroundAttachment = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Scroll: "scroll",
    Fixed: "fixed",
    Local: "local",
};
export const BackgroundClip = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    BorderBox: "border-box",
    PaddingBox: "padding-box",
    ContentBox: "content-box",
    Text: "text",
};
export const BackgroundOrigin = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    BorderBox: "border-box",
    PaddingBox: "padding-box",
    ContentBox: "content-box",
};
export const BackgroundPosition = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Top: "top",
    Bottom: "bottom",
    Left: "left",
    Right: "right",
    Center: "center",
};
export const BackgroundPositionX = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Left: "left",
    Right: "right",
    Center: "center",
};
export const BackgroundPositionY = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Top: "top",
    Center: "center",
    Bottom: "bottom",
};
export const BackgroundRepeat = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    RepeatX: "repeat-x",
    RepeatY: "repeat-y",
    Repeat: "repeat",
    Space: "space",
    Round: "round",
    NoRepeat: "no-repeat",
};
export const BackgroundSize = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Cover: "cover",
    Contain: "contain",
};
export const BlockSize = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    MaxContent: "max-content",
    MinContent: "min-content",
};
export const BorderBlockStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Dashed: "dashed",
    Dotted: "dotted",
    Groove: "groove",
};
export const BorderBlockWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Thick: "thick",
};
export const BorderBlockEndStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Dashed: "dashed",
    Dotted: "dotted",
    Groove: "groove",
};
export const BorderBlockEndWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Thick: "thick",
};
export const BorderBlockStartStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Dashed: "dashed",
    Dotted: "dotted",
    Groove: "groove",
};
export const BorderBlockStartWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Thick: "thick",
};
export const BorderBottomStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Hidden: "hidden",
    Dotted: "dotted",
    Dashed: "dashed",
    Solid: "solid",
    Double: "double",
    Groove: "groove",
    Ridge: "ridge",
    Inset: "inset",
    Outset: "outset",
};
export const BorderBottomWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Thin: "thin",
    Medium: "medium",
    Thick: "thick",
};
export const BorderCollapse = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Collapse: "collapse",
    Seperate: "seperate",
};
export const BorderImageRepeat = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Stretch: "stretch",
    Repeat: "repeat",
    Round: "round",
    Space: "space",
};
export const BorderImageSlice = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Fill: "fill",
};
export const BorderInlineStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Dashed: "dashed",
    Dotted: "dotted",
    Groove: "groove",
};
export const BorderInlineEndStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Dashed: "dashed",
    Dotted: "dotted",
    Groove: "groove",
};
export const BorderInlineStartStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Dashed: "dashed",
    Dotted: "dotted",
    Groove: "groove",
};
export const BorderLeftStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Hidden: "hidden",
    Dotted: "dotted",
    Dashed: "dashed",
    Solid: "solid",
    Double: "double",
    Groove: "groove",
    Ridge: "ridge",
    Inset: "inset",
    Outset: "outset",
};
export const BorderRightStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Hidden: "hidden",
    Dotted: "dotted",
    Dashed: "dashed",
    Solid: "solid",
    Double: "double",
    Groove: "groove",
    Ridge: "ridge",
    Inset: "inset",
    Outset: "outset",
};
export const BorderStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Hidden: "hidden",
    Dotted: "dotted",
    Dashed: "dashed",
    Solid: "solid",
    Double: "double",
    Groove: "groove",
    Ridge: "ridge",
    Inset: "inset",
    Outset: "outset",
};
export const BorderTopStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Hidden: "hidden",
    Dotted: "dotted",
    Dashed: "dashed",
    Solid: "solid",
    Double: "double",
    Groove: "groove",
    Ridge: "ridge",
    Inset: "inset",
    Outset: "outset",
};
export const Bottom = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const BoxDecorationBreak = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Slice: "slice",
    Clone: "clone",
};
export const BoxShadow = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const BoxSizing = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    BorderBox: "border-box",
    BoxSizing: "box-sizing",
};
export const BreakAfter = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Avoid: "avoid",
    Always: "always",
    All: "all",
    AvoidPage: "avoid-page",
    Page: "page",
    Left: "left",
    Right: "right",
    Recto: "recto",
    Verso: "verso",
    AvoidColumn: "avoid-column",
    Column: "column",
    AvoidRegion: "avoid-region",
    Region: "region",
};
export const BreakBefore = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Avoid: "avoid",
    Always: "always",
    All: "all",
    AvoidPage: "avoid-page",
    Page: "page",
    Left: "left",
    Right: "right",
    Recto: "recto",
    Verso: "verso",
    AvoidColumn: "avoid-column",
    Column: "column",
    AvoidRegion: "avoid-region",
    Region: "region",
};
export const BreakInside = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Avoid: "avoid",
    AvoidPage: "avoid-page",
    AvoidColumn: "avoid-column",
    AvoidRegion: "avoid-region",
};
export const CaptionSide = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Top: "top",
    Bottom: "bottom",
    BlockStart: "block-start",
    BlockEnd: "block-end",
    InlineStart: "inline-start",
    InlineEnd: "inline-end",
};
export const CaretColor = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Transparent: "transparent",
    Currentcolor: "currentcolor",
};
export const Clear = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Left: "left",
    Right: "right",
    Both: "both",
    InlineStart: "inline-start",
    InlineEnd: "inline-end",
};
export const Clip = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const ClipPath = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MarginBox: "margin-box",
    BorderBox: "border-box",
    PaddingBox: "padding-box",
    ContentBox: "content-box",
    FillBox: "fill-box",
    Stroke: "stroke",
    ViewBox: "view-box",
};
export const ColorScheme = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    Light: "light",
    Dark: "dark",
};
export const ColumnCount = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const ColumnFill = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Balance: "balance",
    BalanceAll: "balance-all",
};
export const ColumnGap = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
};
export const ColumnRuleStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Hidden: "hidden",
    Dotted: "dotted",
    Dashed: "dashed",
    Solid: "solid",
    Double: "double",
    Groove: "groove",
    Ridge: "ridge",
    Inset: "inset",
    Outset: "outset",
};
export const ColumnRuleWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Thin: "thin",
    Medium: "medium",
    Thick: "thick",
};
export const ColumnSpan = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    All: "all",
};
export const ColumnWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const Columns = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const Contain = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Strict: "strict",
    Content: "content",
    Size: "size",
    Layout: "layout",
    Style: "style",
    Paint: "paint",
};
export const Content = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    None: "none",
    OpenQuote: "open-quote",
    CloseQuote: "close-quote",
    NoOpenQuote: "no-open-quote",
    NoCloseQuote: "no-close-quote",
};
export const ContentVisibility = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Visible: "visible",
    Hidden: "hidden",
    Auto: "auto",
};
export const Cursor = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Default: "default",
    None: "none",
    ContextMenu: "context-menu",
    Help: "help",
    Pointer: "pointer",
    Progress: "progress",
    Wait: "wait",
    Cell: "cell",
    Crosshair: "crosshair",
    Text: "text",
    VerticalText: "vertical-text",
    Alias: "alias",
    Move: "move",
    NoDrop: "no-drop",
    NotAllowed: "not-allowed",
    Grab: "grab",
    Grabbing: "grabbing",
    NResize: "n-resize",
    EResize: "e-resize",
    WResize: "w-resize",
    NeResize: "ne-resize",
    NwResize: "nw-resize",
    SeResize: "se-resize",
    SwResize: "sw-resize",
    EwResize: "ew-resize",
    NsResize: "ns-resize",
    NsResize: "ns-resize",
    NeswResize: "nesw-resize",
    NwseResize: "nwse-resize",
    ZoomIn: "zoom-in",
    ZoomOut: "zoom-out",
};
export const Direction = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Ltr: "ltr",
    Rtl: "rtl",
};
export const Display = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Block: "block",
    Inline: "inline",
    InlineBlock: "inline-block",
    Flex: "flex",
    InlineFlex: "inline-flex",
    Grid: "grid",
    InlineGrid: "inline-grid",
    FlowRoot: "flow-root",
    None: "none",
    Contents: "contents",
    Table: "table",
    TableRow: "table-row",
};
export const EmptyCells = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Show: "show",
    Hide: "hide",
};
export const Filter = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const Flex = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    None: "none",
};
export const FlexBasis = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    MaxContent: "max-content",
    MinContent: "min-content",
    FitContent: "fit-content",
    Auto: "auto",
};
export const FlexDirection = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Row: "row",
    RowReverse: "row-reverse",
    Column: "column",
    ColumnReverse: "column-reverse",
};
export const FlexWrap = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Nowrap: "nowrap",
    Wrap: "wrap",
    WrapReverse: "wrap-reverse",
};
export const Float = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Left: "left",
    Right: "right",
    None: "none",
    InlineStart: "inline-start",
    InlineEnd: "inline-end",
};
export const FontFamily = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Serif: "serif",
    SansSerif: "sans-serif",
    Monospace: "monospace",
    Cursive: "cursive",
    Fantasy: "fantasy",
    SystemUi: "system-ui",
    UiSerif: "ui-serif",
    UiSansSerif: "ui-sans-serif",
    UiMonospace: "ui-monospace",
    UiRounded: "ui-rounded",
    Emoji: "emoji",
    Math: "math",
    Fangsong: "fangsong",
};
export const FontKerning = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Normal: "normal",
    None: "none",
};
export const FontSize = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    XxSmall: "xx-small",
    XSmall: "x-small",
    Small: "small",
    Medium: "medium",
    Large: "large",
    XLarge: "x-large",
    XxLarge: "xx-large",
    XxxLarge: "xxx-large",
};
export const FontSizeAdjust = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const FontStretch = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    UltraCondensed: "ultra-condensed",
    ExtraCondensed: "extra-condensed",
    Condensed: "condensed",
    SemiCondensed: "semi-condensed",
    Normal: "normal",
    SemiExpanded: "semi-expanded",
    Expanded: "expanded",
    ExtraExpanded: "extra-expanded",
    UltraExpanded: "ultra-expanded",
};
export const FontStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    Italic: "italic",
    Oblique: "oblique",
};
export const FontSynthesis = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Weight: "weight",
    Style: "style",
    SmallCaps: "small-caps",
};
export const FontWeight = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    Bold: "bold",
    Lighter: "lighter",
    Bolder: "bolder",
    100: "100",
    200: "200",
    300: "300",
    400: "400",
    500: "500",
    600: "600",
    700: "700",
    800: "800",
    900: "900",
};
export const ForcedColorAdjust = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    None: "none",
};
export const Grid = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const GridAutoColumns = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    MinContent: "min-content",
    MaxContent: "max-content",
    Auto: "auto",
};
export const GridAutoFlow = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Row: "row",
    Column: "column",
    Dense: "dense",
};
export const GridAutoRows = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    MinContent: "min-content",
    MaxContent: "max-content",
    Auto: "auto",
};
export const GridColumn = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const GridColumnEnd = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const GridColumnGap = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const GridRow = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const GridRowEnd = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const GridRowGap = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const GridTemplate = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const GridTemplateAreas = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const GridTemplateColumns = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const GridTemplateRows = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const HangingPunctuation = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    First: "first",
    Last: "last",
    ForceEnd: "force-end",
    AllowEnd: "allow-end",
};
export const Height = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    MaxContent: "max-content",
    MinContent: "min-content",
    Auto: "auto",
};
export const Hyphens = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Manual: "manual",
    Auto: "auto",
};
export const Isolation = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Isolate: "isolate",
};
export const ImageOrientation = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    FromImage: "from-image",
};
export const ImageRendering = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    CrispEdge: "crisp-edge",
    Pixelated: "pixelated",
};
export const ImageResolution = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    FromImage: "from-image",
};
export const InitialLetter = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
};
export const InlineSize = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    MaxContent: "max-content",
    MinContent: "min-content",
};
export const Inset = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const InsetBlock = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const InsetBlockStart = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const InsetInlineStart = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const JustifyContent = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Center: "center",
    Start: "start",
    End: "end",
    FlexStart: "flex-start",
    FlexEnd: "flex-end",
    Left: "left",
    Right: "right",
    Normal: "normal",
    SpaceBetween: "space-between",
    SpaceAround: "space-around",
    Stretch: "stretch",
    SafeCenter: "safe center",
    UnsafeCenter: "unsafe center",
};
export const JustifyItems = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Center: "center",
    Start: "start",
    End: "end",
    FlexStart: "flex-start",
    FlexEnd: "flex-end",
    Left: "left",
    Right: "right",
    Normal: "normal",
    SpaceBetween: "space-between",
    SpaceAround: "space-around",
    Stretch: "stretch",
    SafeCenter: "safe center",
    UnsafeCenter: "unsafe center",
    SelfStart: "self-start",
    SelfEnd: "self-end",
    Baseline: "baseline",
    FirstBaseline: "first baseline",
    LastBaseline: "last baseline",
    LegacyRight: "legacy right",
    LegacyLeft: "legacy left",
    LegacyCenter: "legacy center",
};
export const JustifySelf = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Normal: "normal",
    Stretch: "stretch",
    Center: "center",
    Start: "start",
    End: "end",
    FlexStart: "flex-start",
    FlexEnd: "flex-end",
    SelfStart: "self-start",
    SelfEnd: "self-end",
    Left: "left",
    Right: "right",
    Baseline: "baseline",
    FirstBaseline: "first baseline",
    LastBaseline: "last baseline",
    SafeCenter: "safe center",
    UnsafeCenter: "unsafe center",
};
export const Left = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const LetterSpacing = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
};
export const LineHeight = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
};
export const LineBreak = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Loose: "loose",
    Normal: "normal",
    Strict: "strict",
    Anywhere: "anywhere",
};
export const ListStyleImage = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const ListStylePosition = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Inside: "inside",
    Outside: "outside",
};
export const ListStyleType = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Disc: "disc",
    Circle: "circle",
    Square: "square",
    Decimal: "decimal",
    Georgian: "georgian",
    TradChineseInformal: "trad-chinese-informal",
    Kannada: "kannada",
    DecimalLeadingZero: "decimal-leading-zero",
    LowerRoman: "lower-roman",
    UpperRoman: "upper-roman",
    LowerGreek: "lower-greek",
    LowerAlpha: "lower-alpha",
    UpperAlpha: "upper-alpha",
    Armenian: "armenian",
    Bengali: "bengali",
    Cambodian: "cambodian",
    Devanagari: "devanagari",
    Gujarati: "gujarati",
    Kannada: "kannada",
    Lao: "lao",
    Malayalam: "malayalam",
    Myanmar: "myanmar",
    Oriya: "oriya",
    Telugu: "telugu",
};
export const Margin = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const MarginBlockEnd = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const MarginBlockStart = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const MarginBottom = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const MarginInline = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const MarginInlineEnd = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const MarginInlineStart = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const MarginLeft = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const MarginRight = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const MarginTop = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const Mask = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const MaskBorderMode = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Luminance: "luminance",
    Alpha: "alpha",
};
export const MaskBorderRepeat = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Stretch: "stretch",
    Repeat: "repeat",
    Round: "round",
    Space: "space",
};
export const MaskBorderSource = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const MaskBorderWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const MaskClip = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    ContentBox: "content-box",
    PaddingBox: "padding-box",
    BorderBox: "border-box",
    MarginBox: "margin-box",
    FillBox: "fill-box",
    StrokeBox: "stroke-box",
    ViewBox: "view-box",
    NoClip: "no-clip",
};
export const MaskComposite = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Add: "add",
    Subtract: "subtract",
    Intersect: "intersect",
    Exclude: "exclude",
};
export const MaskImage = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const MaskMode = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Alpha: "alpha",
    Luminance: "luminance",
    MatchSource: "match-source",
};
export const MaskOrigin = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    ContentBox: "content-box",
    PaddingBox: "padding-box",
    BorderBox: "border-box",
    MarginBox: "margin-box",
    FillBox: "fill-box",
    StrokeBox: "stroke-box",
    ViewBox: "view-box",
    Content: "content",
    Padding: "padding",
    Border: "border",
};
export const MaskPosition = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Top: "top",
    Bottom: "bottom",
    Left: "left",
    Right: "right",
    Center: "center",
};
export const MaskRepeat = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    RepeatX: "repeat-x",
    RepeatY: "repeat-y",
    Repeat: "repeat",
    Space: "space",
    Round: "round",
    NoRepeat: "no-repeat",
};
export const MaskSize = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Cover: "cover",
    Contain: "contain",
};
export const MaskType = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Alpha: "alpha",
    Luminance: "luminance",
};
export const MathStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    Compact: "compact",
};
export const MaxBlockSize = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MaxContent: "max-content",
    MinContent: "min-content",
};
export const MaxInlineSize = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MaxContent: "max-content",
    MinContent: "min-content",
};
export const MinBlockSize = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MaxContent: "max-content",
    MinContent: "min-content",
};
export const MinInlineSize = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MaxContent: "max-content",
    MinContent: "min-content",
};
export const MaxHeight = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MaxContent: "max-content",
    MinContent: "min-content",
};
export const MaxWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MaxContent: "max-content",
    MinContent: "min-content",
};
export const MinHeight = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MaxContent: "max-content",
    MinContent: "min-content",
};
export const MinWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MaxContent: "max-content",
    MinContent: "min-content",
};
export const MixBlendMode = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    Multiply: "multiply",
    Screen: "screen",
    Overlay: "overlay",
    Darken: "darken",
    Lighten: "lighten",
    ColorDodge: "color-dodge",
    ColorBurn: "color-burn",
    HardLight: "hard-light",
    SoftLight: "soft-light",
    Difference: "difference",
    Exclusion: "exclusion",
    Hue: "hue",
    Saturation: "saturation",
    Color: "color",
    Luminosity: "luminosity",
};
export const ObjectFit = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Contain: "contain",
    Cover: "cover",
    Fill: "fill",
    None: "none",
    ScaleDown: "scale-down",
};
export const ObjectPosition = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Top: "top",
    Bottom: "bottom",
    Left: "left",
    Right: "right",
    Center: "center",
};
export const Offset = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Auto: "auto",
};
export const OffsetAnchor = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Top: "top",
    Bottom: "bottom",
    Left: "left",
    Right: "right",
    Center: "center",
    Auto: "auto",
};
export const OffsetPath = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MarginBox: "margin-box",
    StrokeBox: "stroke-box",
};
export const OffsetPosition = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Top: "top",
    Bottom: "bottom",
    Left: "left",
    Right: "right",
    Center: "center",
    Auto: "auto",
};
export const OffsetRotate = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const OutlineStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    None: "none",
    Dotted: "dotted",
    Dashed: "dashed",
    Solid: "solid",
    Double: "double",
    Groove: "groove",
    Ridge: "ridge",
    Inset: "inset",
    Outset: "outset",
};
export const OutlineWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Thin: "thin",
    Medium: "medium",
    Thick: "thick",
};
export const Overflow = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Visible: "visible",
    Hidden: "hidden",
    Clip: "clip",
    Scroll: "scroll",
    Auto: "auto",
};
export const OverflowAnchor = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    None: "none",
};
export const OverflowBlock = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Visible: "visible",
    Hidden: "hidden",
    Scroll: "scroll",
    Auto: "auto",
};
export const OverflowInline = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Visible: "visible",
    Hidden: "hidden",
    Scroll: "scroll",
    Auto: "auto",
};
export const OverflowWrap = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    BreakWord: "break-word",
    Anywhere: "anywhere",
};
export const OverflowX = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Visible: "visible",
    Hidden: "hidden",
    Clip: "clip",
    Scroll: "scroll",
    Auto: "auto",
};
export const OverflowY = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Visible: "visible",
    Hidden: "hidden",
    Clip: "clip",
    Scroll: "scroll",
    Auto: "auto",
};
export const OverscrollBehavior = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Contain: "contain",
    None: "none",
};
export const OverscrollBehaviorBlock = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Contain: "contain",
    None: "none",
};
export const OverscrollBehaviorInline = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Contain: "contain",
    None: "none",
};
export const OverscrollBehaviorX = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Contain: "contain",
    None: "none",
};
export const OverscrollBehaviorY = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Contain: "contain",
    None: "none",
};
export const Perspective = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const PerspectiveOrigin = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Top: "top",
    Center: "center",
    Right: "right",
};
export const PlaceContent = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Start: "start",
    End: "end",
    FlexStart: "flex-start",
    FlexEnd: "flex-end",
    Center: "center",
    Center: "center",
    Left: "left",
    Right: "right",
    SpaceBetween: "space-between",
    Baseline: "baseline",
    FirstBaseline: "first baseline",
    LastBaseline: "last baseline",
    SpaceEvenly: "space-evenly",
    Stretch: "stretch",
    Safe: "safe",
    Unsafe: "unsafe",
};
export const PlaceItems = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Start: "start",
    End: "end",
    FlexStart: "flex-start",
    FlexEnd: "flex-end",
    Center: "center",
    Center: "center",
    Left: "left",
    Right: "right",
    SpaceBetween: "space-between",
    Baseline: "baseline",
    FirstBaseline: "first baseline",
    LastBaseline: "last baseline",
    SpaceEvenly: "space-evenly",
    Stretch: "stretch",
    Safe: "safe",
    Unsafe: "unsafe",
    Normal: "normal",
    Legacy: "legacy",
    SelfStart: "self-start",
    SelfEnd: "self-end",
};
export const PointerEvents = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    None: "none",
    VisiblePainted: "visiblePainted",
    VisibleFill: "visibleFill",
    VisibleStroke: "visibleStroke",
    Visible: "visible",
    Painted: "painted",
    Fill: "fill",
    Stroke: "stroke",
    All: "all",
};
export const Position = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Static: "static",
    Relative: "relative",
    Absolute: "absolute",
    Fixed: "fixed",
    Sticky: "sticky",
};
export const Quotes = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Auto: "auto",
};
export const Resize = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
};
export const Rotate = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const RubyAlign = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Start: "start",
    Center: "center",
    SpaceBetween: "space-between",
    SpaceAround: "space-around",
};
export const RubyPosition = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Over: "over",
    Under: "under",
    InterCharacter: "inter-character",
    Alternate: "alternate",
};
export const Scale = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
};
export const ScrollBehavior = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Smooth: "smooth",
};
export const ScrollSnapAlign = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Start: "start",
    End: "end",
    Center: "center",
};
export const ScrollSnapStop = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    Always: "always",
};
export const ScrollSnapType = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    X: "x",
    Y: "y",
    Block: "block",
    Inline: "inline",
    Both: "both",
    Mandatory: "mandatory",
    Proximity: "proximity",
};
export const ScrollbarGutter = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Stable: "stable",
    BothEdges: "both-edges",
};
export const ScrollbarWidth = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Thin: "thin",
    None: "none",
};
export const ShapeOutside = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    MarginBox: "margin-box",
    ContentBox: "content-box",
    BorderBox: "border-box",
    PaddingBox: "padding-box",
};
export const TableLayout = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Fixed: "fixed",
};
export const TextAlign = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Start: "start",
    End: "end",
    Left: "left",
    Right: "right",
    Center: "center",
    Justify: "justify",
    JustifyAll: "justify-all",
    MatchParent: "match-parent",
};
export const TextAlignLast = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Start: "start",
    End: "end",
    Left: "left",
    Right: "right",
    Center: "center",
    Justify: "justify",
};
export const TextCombineUpright = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    All: "all",
};
export const TextDecoration = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const TextDecorationLine = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Underline: "underline",
    Overline: "overline",
    LineThrough: "line-through",
    Blink: "blink",
};
export const TextDecorationSkip = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Objects: "objects",
    Spaces: "spaces",
    Edges: "edges",
    BoxDecoration: "box-decoration",
    LeadingSpaces: "leading-spaces",
    TrailingSpaces: "trailing-spaces",
};
export const TextDecorationSkipInk = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Auto: "auto",
    All: "all",
};
export const TextDecorationStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Solid: "solid",
    Double: "double",
    Dotted: "dotted",
    Dashed: "dashed",
    Wavy: "wavy",
};
export const TextDecorationThickness = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    FromFont: "from-font",
};
export const TextEmphasis = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const TextEmphasisPosition = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Over: "over",
    Under: "under",
    Right: "right",
    Left: "left",
};
export const TextEmphasisStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Filled: "filled",
    Open: "open",
    Dot: "dot",
    Circle: "circle",
    DoubleCircle: "double-circle",
    Triangle: "triangle",
    Sesame: "sesame",
};
export const TextJustify = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Auto: "auto",
    InterWord: "inter-word",
    InterCharacter: "inter-character",
    Distribute: "distribute",
};
export const TextOrientation = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Mixed: "mixed",
    Upright: "upright",
    SidewaysRight: "sideways-right",
    Sideways: "sideways",
    UseGlyphOrientation: "use-glyph-orientation",
};
export const TextOverflow = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Clip: "clip",
    Ellipsis: "ellipsis",
};
export const TextRendering = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    OptimizeSpeed: "optimizeSpeed",
    OptimizeLegibility: "optimizeLegibility",
    GeometricPrecision: "geometricPrecision",
};
export const TextTransform = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Capitalize: "capitalize",
    Uppercase: "uppercase",
    Lowercase: "lowercase",
    FullWidth: "full-width",
    FullSizeKana: "full-size-kana",
};
export const TextUnderlineOffset = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const TextUnderlinePosition = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    Under: "under",
    Left: "left",
    Right: "right",
};
export const Top = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
export const TouchAction = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
    None: "none",
    PanX: "pan-x",
    PanY: "pan-y",
    Manipulation: "manipulation",
    PinchZoom: "pinch-zoom",
};
export const TransformBox = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    ContentBox: "content-box",
    BorderBox: "border-box",
    FillBox: "fill-box",
    StrokeBox: "stroke-box",
    ViewBox: "view-box",
};
export const TransformOrigin = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Left: "left",
    Center: "center",
    Right: "right",
    Top: "top",
    Bottom: "bottom",
};
export const TransformStyle = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Flat: "flat",
    Preserve3d: "preserve-3d",
};
export const TransitionTimingFunction = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Ease: "ease",
    EaseIn: "ease-in",
    EaseOut: "ease-out",
    EaseInOut: "ease-in-out",
    Linear: "linear",
    StepStart: "step-start",
    StepEnd: "step-end",
};
export const Translate = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
};
export const UserSelect = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    None: "none",
    Auto: "auto",
    Text: "text",
    Contain: "contain",
    All: "all",
};
export const VerticalAlign = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Baseline: "baseline",
    Sub: "sub",
    Super: "super",
    TextTop: "text-top",
    TextBottom: "text-bottom",
    Middle: "middle",
    Top: "top",
    Bottom: "bottom",
};
export const Visibility = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Visible: "visible",
    Hidden: "hidden",
    Collapse: "collapse",
};
export const WhiteSpace = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    Nowrap: "nowrap",
    Pre: "pre",
    PreWrap: "pre-wrap",
    PreLine: "pre-line",
    BreakSpaces: "break-spaces",
};
export const Width = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    MaxContent: "max-content",
    MinContent: "min-content",
    Auto: "auto",
};
export const WordBreak = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    BreakAll: "break-all",
    KeepAll: "keep-all",
    BreakWord: "break-word",
};
export const WordSpacing = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
};
export const WordWrap = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Normal: "normal",
    BreakWord: "break-word",
    Anywhere: "anywhere",
};
export const WritingMode = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    HorizontalTb: "horizontal-tb",
    VerticalRl: "vertical-rl",
    VerticalLr: "vertical-lr",
};
export const ZIndex = {
    Inherit: "inherit",
    Initial: "initial",
    Revert: "revert",
    Unset: "unset",
    Revert: "revert",
    RevertLayer: "revert-layer",
    Auto: "auto",
};
