const COLOR = "Color";

const globalValues = [
    "inherit",
    "initial",
    "revert",
    "unset",
    "revert",
    "revert-layer",
];

const List = {
    accentColor: {
        css: "accent-color",
        values: ["auto"],
        methods: [],
        type: COLOR,
        support: [],
    },
    alignContent: {
        css: "align-content",
        values: [
            "center",
            "start",
            "end",
            "flex-start",
            "flex-end",
            "normal",
            "baseline",
            "first baseline",
            "last baseline",
            "space-between",
            "space-around",
            "space-evenly",
            "stretch",
            "safe center",
            "unsafe center",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    alignItems: {
        css: "align-items",
        values: [
            "center",
            "start",
            "end",
            "flex-start",
            "flex-end",
            "normal",
            "baseline",
            "first baseline",
            "last baseline",
            "stretch",
            "safe center",
            "unsafe center",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    alignSelf: {
        css: "align-self",
        values: [
            "center",
            "start",
            "end",
            "flex-start",
            "flex-end",
            "normal",
            "baseline",
            "first baseline",
            "last baseline",
            "space-between",
            "space-around",
            "space-evenly",
            "self-start",
            "self-end",
            "stretch",
            "safe center",
            "unsafe center",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    alignTracks: {
        css: "align-tracks",
        values: ["start", "space-between", "center"],
        methods: [],
        type: "string",
        support: [],
    },
    all: { css: "all", values: [], methods: [], type: "string", support: [] },
    animation: {
        css: "animation",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    animationDelay: {
        css: "animation-delay",
        values: [],
        methods: [,],
        type: "string",
        support: [],
    },
    animationDuration: {
        css: "animation-duration",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    animationFillMode: {
        css: "animation-fill-mode",
        values: ["none", "forwards", "backwards", "both"],
        methods: [],
        type: "string",
        support: [],
    },
    animationIterationCount: {
        css: "animation-iteration-count",
        values: ["infinite"],
        methods: [],
        type: "number",
        support: [],
    },
    animationName: {
        css: "animation-name",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    animationPlayState: {
        css: "animation-play-state",
        values: ["running", "paused"],
        methods: [],
        type: "string",
        support: [],
    },
    animationTimingFunction: {
        css: "animation-timing-function",
        values: [
            "ease",
            "ease-in",
            "ease-out",
            "ease-in-out",
            "linear",
            "step-start",
            "step-end",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    appearance: {
        css: "appearance",
        values: [
            "none",
            "auto",
            "menulist-button",
            "textfield",
            "button",
            "searchfield",
            "textarea",
            "push-button",
            "slide-horizontal",
            "checkbox",
            "radio",
            "square-button",
            "menulist",
            "meter",
            "progress-bar",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    ascentOverride: {
        css: "ascent-override",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    aspectRatio: {
        css: "aspect-ratio",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    backdropFilter: {
        css: "backdrop-filter",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    backfaceVisibility: {
        css: "backface-visibility",
        values: ["hidden", "visible"],
        methods: [],
        type: "string",
        support: [],
    },
    background: {
        css: "background",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    backgroundAttachment: {
        css: "background-attachment",
        values: ["scroll", "fixed", "local"],
        methods: [],
        type: "string",
        support: [],
    },
    backgroundBlendMode: {
        css: "background-blend-mode",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    backgroundClip: {
        css: "background-clip",
        values: ["border-box", "padding-box", "content-box", "text"],
        methods: [],
        type: "string",
        support: [],
    },
    backgroundColor: {
        css: "background-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    backgroundImage: {
        css: "background-image",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    backgroundOrigin: {
        css: "background-origin",
        values: ["border-box", "padding-box", "content-box"],
        methods: [],
        type: "string",
        support: [],
    },
    backgroundPosition: {
        css: "background-position",
        values: ["top", "bottom", "left", "right", "center"],
        methods: [],
        type: "string",
        support: [],
    },
    backgroundPositionX: {
        css: "background-position-x",
        values: ["left", "right", "center"],
        methods: [],
        type: "string",
        support: [],
    },
    backgroundPositionY: {
        css: "background-position-y",
        values: ["top", "center", "bottom"],
        methods: [],
        type: "string",
        support: [],
    },
    backgroundRepeat: {
        css: "background-repeat",
        values: [
            "repeat-x",
            "repeat-y",
            "repeat",
            "space",
            "round",
            "no-repeat",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    backgroundSize: {
        css: "background-size",
        values: ["cover", "contain"],
        methods: [],
        type: "string",
        support: [],
    },
    blockSize: {
        css: "block-size",
        values: ["max-content", "min-content"],
        methods: [],
        type: "string",
        support: [],
    },
    borderBlock: {
        css: "border-block",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderBlockColor: {
        css: "border-block-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderBlockStyle: {
        css: "border-block-style",
        values: ["dashed", "dotted", "groove"],
        methods: [],
        type: "string",
        support: [],
    },
    borderBlockWidth: {
        css: "border-block-width",
        values: ["thick"],
        methods: [],
        type: "string",
        support: [],
    },
    borderBlockEnd: {
        css: "border-block-end",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderBlockEndColor: {
        css: "border-block-end-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderBlockEndStyle: {
        css: "border-block-end-style",
        values: ["dashed", "dotted", "groove"],
        methods: [],
        type: "string",
        support: [],
    },
    borderBlockEndWidth: {
        css: "border-block-end-width",
        values: ["thick"],
        methods: [],
        type: "string",
        support: [],
    },
    borderBlockStart: {
        css: "border-block-start",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderBlockStartColor: {
        css: "border-block-start-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderBlockStartStyle: {
        css: "border-block-start-style",
        values: ["dashed", "dotted", "groove"],
        methods: [],
        type: "string",
        support: [],
    },
    borderBlockStartWidth: {
        css: "border-block-start-width",
        values: ["thick"],
        methods: [],
        type: "string",
        support: [],
    },
    border: {
        css: "border",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderBottom: {
        css: "border-bottom",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderBottomColor: {
        css: "border-bottom-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderBottomLeftRadius: {
        css: "border-bottom-left-radius",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderBottomRightRadius: {
        css: "border-bottom-right-radius",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderBottomStyle: {
        css: "border-bottom-style",
        values: [
            "none",
            "hidden",
            "dotted",
            "dashed",
            "solid",
            "double",
            "groove",
            "ridge",
            "inset",
            "outset",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    borderBottomWidth: {
        css: "border-bottom-width",
        values: ["thin", "medium", "thick"],
        methods: [],
        type: "string",
        support: [],
    },
    borderCollapse: {
        css: "border-collapse",
        values: ["collapse", "seperate"],
        methods: [],
        type: "string",
        support: [],
    },
    borderColor: {
        css: "border-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderEndEndRadius: {
        css: "border-end-end-radius",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderEndStartRadius: {
        css: "border-end-start-radius",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderStartEndRadius: {
        css: "border-start-end-radius",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderStartStartRadius: {
        css: "border-start-start-radius",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderImage: {
        css: "border-image",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderImageOutset: {
        css: "border-outset",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderImageRepeat: {
        css: "border-image-repeat",
        values: ["stretch", "repeat", "round", "space"],
        methods: [],
        type: "string",
        support: [],
    },
    borderImageSlice: {
        css: "border-image-slice",
        values: ["fill"],
        methods: [],
        type: "string",
        support: [],
    },
    borderImageSource: {
        css: "border-image-source",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderImageWidth: {
        css: "border-image-width",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderInline: {
        css: "border-inline",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderInlineColor: {
        css: "border-inline-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderInlineStyle: {
        css: "border-inline-style",
        values: ["dashed", "dotted", "groove"],
        methods: [],
        type: "string",
        support: [],
    },
    borderInlineWidth: {
        css: "border-inline-width",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderInlineEnd: {
        css: "border-inline-end",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderInlineEndColor: {
        css: "border-inline-end-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderInlineEndStyle: {
        css: "border-inline-end-style",
        values: ["dashed", "dotted", "groove"],
        methods: [],
        type: "string",
        support: [],
    },
    borderInlineEndWidth: {
        css: "border-inline-end-width",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderStartEnd: {
        css: "border-start-end",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderInlineStartColor: {
        css: "border-inline-start-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderInlineStartStyle: {
        css: "border-inline-start-style",
        values: ["dashed", "dotted", "groove"],
        methods: [],
        type: "string",
        support: [],
    },
    borderInlineStartWidth: {
        css: "border-inline-start-width",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderLeft: {
        css: "border-left",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderLeftColor: {
        css: "border-left-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderLeftStyle: {
        css: "border-left-style",
        values: [
            "none",
            "hidden",
            "dotted",
            "dashed",
            "solid",
            "double",
            "groove",
            "ridge",
            "inset",
            "outset",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    borderLeftWidth: {
        css: "border-left-width",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderRadius: {
        css: "border-radius",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderRight: {
        css: "border-right",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderRightColor: {
        css: "border-right-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderRightStyle: {
        css: "border-right-style",
        values: [
            "none",
            "hidden",
            "dotted",
            "dashed",
            "solid",
            "double",
            "groove",
            "ridge",
            "inset",
            "outset",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    borderRightWidth: {
        css: "border-right-width",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderSpacing: {
        css: "border-spacing",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderStyle: {
        css: "border-style",
        values: [
            "none",
            "hidden",
            "dotted",
            "dashed",
            "solid",
            "double",
            "groove",
            "ridge",
            "inset",
            "outset",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    borderTop: {
        css: "border-top",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderTopColor: {
        css: "border-top-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    borderTopLeftRadius: {
        css: "border-top-left-radius",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderTopRightRadius: {
        css: "border-top-right-radius",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderTopStyle: {
        css: "border-top-style",
        values: [
            "none",
            "hidden",
            "dotted",
            "dashed",
            "solid",
            "double",
            "groove",
            "ridge",
            "inset",
            "outset",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    borderTopWidth: {
        css: "border-top-width",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    borderWidth: {
        css: "border-width",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    bottom: {
        css: "bottom",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    boxDecorationBreak: {
        css: "box-decoration-break",
        values: ["slice", "clone"],
        methods: [],
        type: "string",
        support: [],
    },
    boxShadow: {
        css: "box-shadow",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    boxSizing: {
        css: "box-sizing",
        values: ["border-box", "box-sizing"],
        methods: [],
        type: "string",
        support: [],
    },
    breakAfter: {
        css: "break-after",
        values: [
            "auto",
            "avoid",
            "always",
            "all",
            "avoid-page",
            "page",
            "left",
            "right",
            "recto",
            "verso",
            "avoid-column",
            "column",
            "avoid-region",
            "region",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    breakBefore: {
        css: "break-before",
        values: [
            "auto",
            "avoid",
            "always",
            "all",
            "avoid-page",
            "page",
            "left",
            "right",
            "recto",
            "verso",
            "avoid-column",
            "column",
            "avoid-region",
            "region",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    breakInside: {
        css: "break-inside",
        values: ["auto", "avoid", "avoid-page", "avoid-column", "avoid-region"],
        methods: [],
        type: "string",
        support: [],
    },
    captionSide: {
        css: "caption-side",
        values: [
            "top",
            "bottom",
            "block-start",
            "block-end",
            "inline-start",
            "inline-end",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    caretColor: {
        css: "caret-color",
        values: ["auto", "transparent", "currentcolor"],
        methods: [],
        type: COLOR,
        support: [],
    },
    clear: {
        css: "clear",
        values: ["none", "left", "right", "both", "inline-start", "inline-end"],
        methods: [],
        type: "string",
        support: [],
    },
    clip: {
        css: "clip",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    clipPath: {
        css: "clip-path",
        values: [
            "none",
            "margin-box",
            "border-box",
            "padding-box",
            "content-box",
            "fill-box",
            "stroke",
            "view-box",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    color: { css: "color", values: [], methods: [], type: COLOR, support: [] },
    colorAdjust: {
        css: "color-adjust",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    colorScheme: {
        css: "color-scheme",
        values: ["normal", "light", "dark"],
        methods: [],
        type: "string",
        support: [],
    },
    columnCount: {
        css: "column-count",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    columnFill: {
        css: "column-fill",
        values: ["auto", "balance", "balance-all"],
        methods: [],
        type: "string",
        support: [],
    },
    columnGap: {
        css: "column-gap",
        values: ["normal"],
        methods: [],
        type: "string",
        support: [],
    },
    columnRule: {
        css: "column-rule",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    columnRuleColor: {
        css: "column-rule-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    columnRuleStyle: {
        css: "column-rule-style",
        values: [
            "none",
            "hidden",
            "dotted",
            "dashed",
            "solid",
            "double",
            "groove",
            "ridge",
            "inset",
            "outset",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    columnRuleWidth: {
        css: "column-rule-width",
        values: ["thin", "medium", "thick"],
        methods: [],
        type: "string",
        support: [],
    },
    columnSpan: {
        css: "column-span",
        values: ["none", "all"],
        methods: [],
        type: "string",
        support: [],
    },
    columnWidth: {
        css: "column-width",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    columns: {
        css: "columns",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    contain: {
        css: "contain",
        values: [
            "none",
            "strict",
            "content",
            "size",
            "layout",
            "style",
            "paint",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    content: {
        css: "content",
        values: [
            "normal",
            "none",
            "open-quote",
            "close-quote",
            "no-open-quote",
            "no-close-quote",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    contentVisibility: {
        css: "content-visibility",
        values: ["visible", "hidden", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    counterIncrement: {
        css: "counter-increment",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    counterReset: {
        css: "counter-reset",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    counterSet: {
        css: "counter-set",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    cursor: {
        css: "cursor",
        values: [
            "auto",
            "default",
            "none",
            "context-menu",
            "help",
            "pointer",
            "progress",
            "wait",
            "cell",
            "crosshair",
            "text",
            "vertical-text",
            "alias",
            "move",
            "no-drop",
            "not-allowed",
            "grab",
            "grabbing",
            "n-resize",
            "e-resize",
            "w-resize",
            "ne-resize",
            "nw-resize",
            "se-resize",
            "sw-resize",
            "ew-resize",
            "ns-resize",
            "ns-resize",
            "nesw-resize",
            "nwse-resize",
            "zoom-in",
            "zoom-out",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    direction: {
        css: "direction",
        values: ["ltr", "rtl"],
        methods: [],
        type: "string",
        support: [],
    },
    display: {
        css: "display",
        values: [
            "block",
            "inline",
            "inline-block",
            "flex",
            "inline-flex",
            "grid",
            "inline-grid",
            "flow-root",
            "none",
            "contents",
            "table",
            "table-row",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    emptyCells: {
        css: "empty-cells",
        values: ["show", "hide"],
        methods: [],
        type: "string",
        support: [],
    },
    filter: {
        css: "filter",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    flex: {
        css: "flex",
        values: ["auto", "none"],
        methods: [],
        type: "string",
        support: [],
    },
    flexBasis: {
        css: "flex-basis",
        values: ["max-content", "min-content", "fit-content", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    flexDirection: {
        css: "flex-direction",
        values: ["row", "row-reverse", "column", "column-reverse"],
        methods: [],
        type: "string",
        support: [],
    },
    flexFlow: {
        css: "flex-flow",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    flexGrow: {
        css: "flex-grow",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    flexShrink: {
        css: "flex-shrink",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    flexWrap: {
        css: "flex-wrap",
        values: ["nowrap", "wrap", "wrap-reverse"],
        methods: [],
        type: "string",
        support: [],
    },
    float: {
        css: "float",
        values: ["left", "right", "none", "inline-start", "inline-end"],
        methods: [],
        type: "string",
        support: [],
    },
    font: { css: "font", values: [], methods: [], type: "string", support: [] },
    fontFamily: {
        css: "font-family",
        values: [
            "serif",
            "sans-serif",
            "monospace",
            "cursive",
            "fantasy",
            "system-ui",
            "ui-serif",
            "ui-sans-serif",
            "ui-monospace",
            "ui-rounded",
            "emoji",
            "math",
            "fangsong",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    fontFeatureSettings: {
        css: "font-feature-settings",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    fontKerning: {
        css: "font-kerning",
        values: ["auto", "normal", "none"],
        methods: [],
        type: "string",
        support: [],
    },
    fontSize: {
        css: "font-size",
        values: [
            "xx-small",
            "x-small",
            "small",
            "medium",
            "large",
            "x-large",
            "xx-large",
            "xxx-large",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    fontSizeAdjust: {
        css: "font-size-adjust",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    fontStretch: {
        css: "font-stretch",
        values: [
            "ultra-condensed",
            "extra-condensed",
            "condensed",
            "semi-condensed",
            "normal",
            "semi-expanded",
            "expanded",
            "extra-expanded",
            "ultra-expanded",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    fontStyle: {
        css: "font-style",
        values: ["normal", "italic", "oblique"],
        methods: [],
        type: "string",
        support: [],
    },
    fontSynthesis: {
        css: "font-synthesis",
        values: ["none", "weight", "style", "small-caps"],
        methods: [],
        type: "string",
        support: [],
    },
    fontVariant: {
        css: "font-variant",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    fontVariantAlternates: {
        css: "font-variant-alternates",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    fontVariantCaps: {
        css: "font-variant-caps",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    fontVariantEastAsian: {
        css: "font-variant-east-asian",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    fontVariantLigatures: {
        css: "font-variant-ligatures",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    fontVariantNumeric: {
        css: "font-variant-numeric",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    fontVariantPosition: {
        css: "font-variant-position",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    fontVariantSettings: {
        css: "font-variant-settings",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    fontWeight: {
        css: "font-weight",
        values: [
            "normal",
            "bold",
            "lighter",
            "bolder",
            "100",
            "200",
            "300",
            "400",
            "500",
            "600",
            "700",
            "800",
            "900",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    forcedColorAdjust: {
        css: "forced-color-adjust",
        values: ["auto", "none"],
        methods: [],
        type: COLOR,
        support: [],
    },
    gap: { css: "gap", values: [], methods: [], type: "string", support: [] },
    grid: {
        css: "grid",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    gridArea: {
        css: "grid-area",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    gridAutoColumns: {
        css: "grid-auto-columns",
        values: ["min-content", "max-content", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    gridAutoFlow: {
        css: "grid-auto-flow",
        values: ["row", "column", "dense"],
        methods: [],
        type: "string",
        support: [],
    },
    gridAutoRows: {
        css: "grid-auto-rows",
        values: ["min-content", "max-content", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    gridColumn: {
        css: "grid-column",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    gridColumnEnd: {
        css: "grid-column-end",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    gridColumnGap: {
        css: "grid-column-gap",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    gridColumnStart: {
        css: "grid-column-start",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    gridGap: {
        css: "grid-gap",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    gridRow: {
        css: "grid-row",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    gridRowEnd: {
        css: "grid-row-end",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    gridRowGap: {
        css: "grid-row-gap",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    gridRowStart: {
        css: "grid-row-start",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    gridTemplate: {
        css: "grid-template",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    gridTemplateAreas: {
        css: "grid-template-areas",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    gridTemplateColumns: {
        css: "grid-template-columns",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    gridTemplateRows: {
        css: "grid-template-rows",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    hangingPunctuation: {
        css: "hanging-punctuation",
        values: ["none", "first", "last", "force-end", "allow-end"],
        methods: [],
        type: "string",
        support: [],
    },
    height: {
        css: "height",
        values: ["max-content", "min-content", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    hyphens: {
        css: "hyphens",
        values: ["none", "manual", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    isolation: {
        css: "isolation",
        values: ["auto", "isolate"],
        methods: [],
        type: "string",
        support: [],
    },
    imageOrientation: {
        css: "image-orientation",
        values: ["none", "from-image"],
        methods: [],
        type: "string",
        support: [],
    },
    imageRendering: {
        css: "image-rendering",
        values: ["auto", "crisp-edge", "pixelated"],
        methods: [],
        type: "string",
        support: [],
    },
    imageResolution: {
        css: "image-resolution",
        values: ["from-image"],
        methods: [],
        type: "string",
        support: [],
    },
    initialLetter: {
        css: "initial-letter",
        values: ["normal"],
        methods: [],
        type: "string",
        support: [],
    },
    inlineSize: {
        css: "inline-size",
        values: ["auto", "max-content", "min-content"],
        methods: [],
        type: "string",
        support: [],
    },
    inset: {
        css: "inset",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    insetBlock: {
        css: "inset-inline",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    insetBlockStart: {
        css: "inset-block-start",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    insetInlineStart: {
        css: "inset-inline-start",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    justifyContent: {
        css: "justify-content",
        values: [
            "center",
            "start",
            "end",
            "flex-start",
            "flex-end",
            "left",
            "right",
            "normal",
            "space-between",
            "space-around",
            "stretch",
            "safe center",
            "unsafe center",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    justifyItems: {
        css: "justify-items",
        values: [
            "center",
            "start",
            "end",
            "flex-start",
            "flex-end",
            "left",
            "right",
            "normal",
            "space-between",
            "space-around",
            "stretch",
            "safe center",
            "unsafe center",
            "self-start",
            "self-end",
            "baseline",
            "first baseline",
            "last baseline",
            "legacy right",
            "legacy left",
            "legacy center",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    justifySelf: {
        css: "justify-self",
        values: [
            "auto",
            "normal",
            "stretch",
            "center",
            "start",
            "end",
            "flex-start",
            "flex-end",
            "self-start",
            "self-end",
            "left",
            "right",
            "baseline",
            "first baseline",
            "last baseline",
            "safe center",
            "unsafe center",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    left: {
        css: "left",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    letterSpacing: {
        css: "letter-spacing",
        values: ["normal"],
        methods: [],
        type: "string",
        support: [],
    },
    lineHeight: {
        css: "line-height",
        values: ["normal"],
        methods: [],
        type: "string",
        support: [],
    },
    lineBreak: {
        css: "line-break",
        values: ["auto", "loose", "normal", "strict", "anywhere"],
        methods: [],
        type: "string",
        support: [],
    },
    listStyle: {
        css: "list-style",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    listStyleImage: {
        css: "list-style-image",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    listStylePosition: {
        css: "list-style-position",
        values: ["inside", "outside"],
        methods: [],
        type: "string",
        support: [],
    },
    listStyleType: {
        css: "list-style-type",
        values: [
            "none",
            "disc",
            "circle",
            "square",
            "decimal",
            "georgian",
            "trad-chinese-informal",
            "kannada",
            "decimal-leading-zero",
            "lower-roman",
            "upper-roman",
            "lower-greek",
            "lower-alpha",
            "upper-alpha",
            "armenian",
            "bengali",
            "cambodian",
            "devanagari",
            "gujarati",
            "kannada",
            "lao",
            "malayalam",
            "myanmar",
            "oriya",
            "telugu",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    margin: {
        css: "margin",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    marginBlock: {
        css: "margin-block",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    marginBlockEnd: {
        css: "margin-block-end",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    marginBlockStart: {
        css: "margin-block-start",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    marginBottom: {
        css: "margin-bottom",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    marginInline: {
        css: "margin-inline",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    marginInlineEnd: {
        css: "margin-inline-end",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    marginInlineStart: {
        css: "margin-inline-start",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    marginLeft: {
        css: "margin-left",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    marginRight: {
        css: "margin-right",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    marginTop: {
        css: "margin-top",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    mask: {
        css: "mask",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    maskBorder: {
        css: "mask-border",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    maskBorderMode: {
        css: "mask-border-mode",
        values: ["luminance", "alpha"],
        methods: [],
        type: "string",
        support: [],
    },
    maskBorderOutset: {
        css: "mast-border-outset",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    maskBorderRepeat: {
        css: "mask-border-repeat",
        values: ["stretch", "repeat", "round", "space"],
        methods: [],
        type: "string",
        support: [],
    },
    maskBorderSlice: {
        css: "mask-border-slice",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    maskBorderSource: {
        css: "mask-border-source",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    maskBorderWidth: {
        css: "mask-border-width",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    maskClip: {
        css: "mask-clip",
        values: [
            "content-box",
            "padding-box",
            "border-box",
            "margin-box",
            "fill-box",
            "stroke-box",
            "view-box",
            "no-clip",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    maskComposite: {
        css: "mask-composite",
        values: ["add", "subtract", "intersect", "exclude"],
        methods: [],
        type: "string",
        support: [],
    },
    maskImage: {
        css: "mask-image",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    maskMode: {
        css: "mask-mode",
        values: ["alpha", "luminance", "match-source"],
        methods: [],
        type: "string",
        support: [],
    },
    maskOrigin: {
        css: "mask-origin",
        values: [
            "content-box",
            "padding-box",
            "border-box",
            "margin-box",
            "fill-box",
            "stroke-box",
            "view-box",
            "content",
            "padding",
            "border",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    maskPosition: {
        css: "mask-position",
        values: ["top", "bottom", "left", "right", "center"],
        methods: [],
        type: "string",
        support: [],
    },
    maskRepeat: {
        css: "mask-repeat",
        values: [
            "repeat-x",
            "repeat-y",
            "repeat",
            "space",
            "round",
            "no-repeat",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    maskSize: {
        css: "mask-size",
        values: ["cover", "contain"],
        methods: [],
        type: "string",
        support: [],
    },
    maskType: {
        css: "mask-type",
        values: ["alpha", "luminance"],
        methods: [],
        type: "string",
        support: [],
    },
    mathStyle: {
        css: "math-style",
        values: ["normal", "compact"],
        methods: [],
        type: "string",
        support: [],
    },
    maxBlockSize: {
        css: "max-block-size",
        values: ["none", "max-content", "min-content"],
        methods: [],
        type: "string",
        support: [],
    },
    maxInlineSize: {
        css: "max-inline-size",
        values: ["none", "max-content", "min-content"],
        methods: [],
        type: "string",
        support: [],
    },
    minBlockSize: {
        css: "min-block-size",
        values: ["none", "max-content", "min-content"],
        methods: [],
        type: "string",
        support: [],
    },
    minInlineSize: {
        css: "min-inline-size",
        values: ["none", "max-content", "min-content"],
        methods: [],
        type: "string",
        support: [],
    },
    maxHeight: {
        css: "max-height",
        values: ["none", "max-content", "min-content"],
        methods: [],
        type: "string",
        support: [],
    },
    maxWidth: {
        css: "max-width",
        values: ["none", "max-content", "min-content"],
        methods: [],
        type: "string",
        support: [],
    },
    minHeight: {
        css: "min-height",
        values: ["none", "max-content", "min-content"],
        methods: [],
        type: "string",
        support: [],
    },
    minWidth: {
        css: "min-width",
        values: ["none", "max-content", "min-content"],
        methods: [],
        type: "string",
        support: [],
    },
    mixBlendMode: {
        css: "mix-blend-mode",
        values: [
            "normal",
            "multiply",
            "screen",
            "overlay",
            "darken",
            "lighten",
            "color-dodge",
            "color-burn",
            "hard-light",
            "soft-light",
            "difference",
            "exclusion",
            "hue",
            "saturation",
            "color",
            "luminosity",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    objectFit: {
        css: "object-fit",
        values: ["contain", "cover", "fill", "none", "scale-down"],
        methods: [],
        type: "string",
        support: [],
    },
    objectPosition: {
        css: "object-position",
        values: ["top", "bottom", "left", "right", "center"],
        methods: [],
        type: "string",
        support: [],
    },
    offset: {
        css: "offset",
        values: ["none", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    offsetAnchor: {
        css: "offset-anchor",
        values: ["top", "bottom", "left", "right", "center", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    offsetDistance: {
        css: "offset-distance",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    offsetPath: {
        css: "offset-path",
        values: ["none", "margin-box", "stroke-box"],
        methods: [],
        type: "string",
        support: [],
    },
    offsetPosition: {
        css: "offset-position",
        values: ["top", "bottom", "left", "right", "center", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    offsetRotate: {
        css: "offset-rotate",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    opacity: {
        css: "opacity",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    order: {
        css: "order",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    orphans: {
        css: "orphans",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    outline: {
        css: "outline",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    outlineColor: {
        css: "outline-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    outlineOffset: {
        css: "outline-offset",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    outlineStyle: {
        css: "outline-style",
        values: [
            "auto",
            "none",
            "dotted",
            "dashed",
            "solid",
            "double",
            "groove",
            "ridge",
            "inset",
            "outset",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    outlineWidth: {
        css: "outline-width",
        values: ["thin", "medium", "thick"],
        methods: [],
        type: "string",
        support: [],
    },
    overflow: {
        css: "overflow",
        values: ["visible", "hidden", "clip", "scroll", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    overflowAnchor: {
        css: "overflow-anchor",
        values: ["auto", "none"],
        methods: [],
        type: "string",
        support: [],
    },
    overflowBlock: {
        css: "overflow-block",
        values: ["visible", "hidden", "scroll", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    overflowClipMargin: {
        css: "overflow-clip-margin",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    overflowInline: {
        css: "overflow-inline",
        values: ["visible", "hidden", "scroll", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    overflowWrap: {
        css: "overflow-wrap",
        values: ["normal", "break-word", "anywhere"],
        methods: [],
        type: "string",
        support: [],
    },
    overflowX: {
        css: "overflow-x",
        values: ["visible", "hidden", "clip", "scroll", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    overflowY: {
        css: "overflow-y",
        values: ["visible", "hidden", "clip", "scroll", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    overscrollBehavior: {
        css: "overscroll-behavior",
        values: ["auto", "contain", "none"],
        methods: [],
        type: "string",
        support: [],
    },
    overscrollBehaviorBlock: {
        css: "overscroll-behavior-block",
        values: ["auto", "contain", "none"],
        methods: [],
        type: "string",
        support: [],
    },
    overscrollBehaviorInline: {
        css: "overscroll-behavior-inline",
        values: ["auto", "contain", "none"],
        methods: [],
        type: "string",
        support: [],
    },
    overscrollBehaviorX: {
        css: "overscroll-behavior-x",
        values: ["auto", "contain", "none"],
        methods: [],
        type: "string",
        support: [],
    },
    overscrollBehaviorY: {
        css: "overscroll-behavior-y",
        values: ["auto", "contain", "none"],
        methods: [],
        type: "string",
        support: [],
    },
    right: {
        css: "right",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    padding: {
        css: "padding",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    paddingBlock: {
        css: "padding-block",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    paddingBlockEnd: {
        css: "padding-block-end",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    paddingBlockStart: {
        css: "padding-block-start",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    paddingBottom: {
        css: "padding-bottom",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    paddingInline: {
        css: "padding-inline",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    paddingInlineEnd: {
        css: "padding-inline-end",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    paddingInlineStart: {
        css: "padding-inline-start",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    paddingLeft: {
        css: "padding-left",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    paddingRight: {
        css: "padding-right",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    paddingTop: {
        css: "padding-top",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    pageBreakAfter: {
        css: "page-break-after",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    pageBreakBefore: {
        css: "page-break-before",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    pageBreakInside: {
        css: "page-break-inside",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    perspective: {
        css: "perspective",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    perspectiveOrigin: {
        css: "perspective-origin",
        values: ["top", "center", "right"],
        methods: [],
        type: "string",
        support: [],
    },
    placeContent: {
        css: "place-content",
        values: [
            "start",
            "end",
            "flex-start",
            "flex-end",
            "center",
            "center",
            "left",
            "right",
            "space-between",
            "baseline",
            "first baseline",
            "last baseline",
            "space-evenly",
            "stretch",
            "safe",
            "unsafe",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    placeItems: {
        css: "place-items",
        values: [
            "start",
            "end",
            "flex-start",
            "flex-end",
            "center",
            "center",
            "left",
            "right",
            "space-between",
            "baseline",
            "first baseline",
            "last baseline",
            "space-evenly",
            "stretch",
            "safe",
            "unsafe",
            "normal",
            "legacy",
            "self-start",
            "self-end",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    pointerEvents: {
        css: "pointer-events",
        values: [
            "auto",
            "none",
            "visiblePainted",
            "visibleFill",
            "visibleStroke",
            "visible",
            "painted",
            "fill",
            "stroke",
            "all",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    position: {
        css: "position",
        values: ["static", "relative", "absolute", "fixed", "sticky"],
        methods: [],
        type: "string",
        support: [],
    },
    quotes: {
        css: "quotes",
        values: ["none", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    resize: {
        css: "resize",
        values: [],
        methods: ["none", "both", "horizontal", "vertical", "block", "inline"],
        type: "string",
        support: [],
    },
    rotate: {
        css: "rotate",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    rowGap: {
        css: "row-gap",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    rubyAlign: {
        css: "ruby-align",
        values: ["start", "center", "space-between", "space-around"],
        methods: [],
        type: "string",
        support: [],
    },
    rubyPosition: {
        css: "ruby-position",
        values: ["over", "under", "inter-character", "alternate"],
        methods: [],
        type: "string",
        support: [],
    },
    scale: {
        css: "scale",
        values: [],
        methods: ["none"],
        type: "string",
        support: [],
    },
    scrollBehavior: {
        css: "scroll-behavior",
        values: ["auto", "smooth"],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMargin: {
        css: "scroll-margin",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMarginBlock: {
        css: "scroll-margin-block",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMarginBlockEnd: {
        css: "scroll-margin-block-end",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMarginBlockStart: {
        css: "scroll-margin-block-start",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMarginBottom: {
        css: "scroll-margin-bottom",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMarginInline: {
        css: "scroll-margin-inline",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMarginInlineEnd: {
        css: "scroll-margin-inline-end",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMarginInlineStart: {
        css: "scroll-margin-inline-start",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMarginLeft: {
        css: "scroll-margin-left",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMarginRight: {
        css: "scroll-margin-right",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollMarginTop: {
        css: "scroll-margin-top",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollPadding: {
        css: "scroll-padding",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollPaddingBlock: {
        css: "scroll-padding-block",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollPaddingBlockEnd: {
        css: "scroll-padding-block-end",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollPaddingBlockStart: {
        css: "scroll-padding-block-start",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollPaddingBottom: {
        css: "scroll-padding-bottom",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollPaddingInline: {
        css: "scroll-padding-inline-end",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollPaddingInlineStart: {
        css: "scroll-padding-inline-start",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollPaddingLeft: {
        css: "scroll-padding-left",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollPaddingRight: {
        css: "scroll-padding-right",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollPaddingTop: {
        css: "scroll-padding-top",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    scrollSnapAlign: {
        css: "scroll-snap-align",
        values: ["none", "start", "end", "center"],
        methods: [],
        type: "string",
        support: [],
    },
    scrollSnapStop: {
        css: "scroll-snap-stop",
        values: ["normal", "always"],
        methods: [],
        type: "string",
        support: [],
    },
    scrollSnapType: {
        css: "scroll-snap-type",
        values: [
            "none",
            "x",
            "y",
            "block",
            "inline",
            "both",
            "mandatory",
            "proximity",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    scrollbarColor: {
        css: "scrollbar-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    scrollbarGutter: {
        css: "scrollbar-gutter",
        values: ["auto", "stable", "both-edges"],
        methods: [],
        type: "string",
        support: [],
    },
    scrollbarWidth: {
        css: "scrollbar-width",
        values: ["auto", "thin", "none"],
        methods: [],
        type: "string",
        support: [],
    },
    shapeImageThreshold: {
        css: "shape-image-threshold",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    shapeMargin: {
        css: "shape-margin",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    shapeOutside: {
        css: "shape-outside",
        values: [
            "none",
            "margin-box",
            "content-box",
            "border-box",
            "padding-box",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    tabSize: {
        css: "tab-size",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    tableLayout: {
        css: "table-layout",
        values: ["auto", "fixed"],
        methods: [],
        type: "string",
        support: [],
    },
    textAlign: {
        css: "text-align",
        values: [
            "start",
            "end",
            "left",
            "right",
            "center",
            "justify",
            "justify-all",
            "match-parent",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    textAlignLast: {
        css: "text-align-last",
        values: ["start", "end", "left", "right", "center", "justify"],
        methods: [],
        type: "string",
        support: [],
    },
    textCombineUpright: {
        css: "text-combine-upright",
        values: ["none", "all"],
        methods: [],
        type: "string",
        support: [],
    },
    textDecoration: {
        css: "text-decoration",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    textDecorationColor: {
        css: "text-decoration-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    textDecorationLine: {
        css: "text-decoration-line",
        values: ["none", "underline", "overline", "line-through", "blink"],
        methods: [],
        type: "string",
        support: [],
    },
    textDecorationSkip: {
        css: "text-decoration-skip",
        values: [
            "none",
            "objects",
            "spaces",
            "edges",
            "box-decoration",
            "leading-spaces",
            "trailing-spaces",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    textDecorationSkipInk: {
        css: "text-decoration-skip-ink",
        values: ["none", "auto", "all"],
        methods: [],
        type: "string",
        support: [],
    },
    textDecorationStyle: {
        css: "text-decoration-style",
        values: ["solid", "double", "dotted", "dashed", "wavy"],
        methods: [],
        type: "string",
        support: [],
    },
    textDecorationThickness: {
        css: "text-decoration-thickness",
        values: ["auto", "from-font"],
        methods: [],
        type: "string",
        support: [],
    },
    textEmphasis: {
        css: "text-emphasis",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    textEmphasisColor: {
        css: "text-emphasis-color",
        values: [],
        methods: [],
        type: COLOR,
        support: [],
    },
    textEmphasisPosition: {
        css: "text-emphasis-position",
        values: ["over", "under", "right", "left"],
        methods: [],
        type: "string",
        support: [],
    },
    textEmphasisStyle: {
        css: "text-emphasis-style",
        values: [
            "none",
            "filled",
            "open",
            "dot",
            "circle",
            "double-circle",
            "triangle",
            "sesame",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    textIndent: {
        css: "text-indent",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    textJustify: {
        css: "text-justify",
        values: ["none", "auto", "inter-word", "inter-character", "distribute"],
        methods: [],
        type: "string",
        support: [],
    },
    textOrientation: {
        css: "text-orientation",
        values: [
            "mixed",
            "upright",
            "sideways-right",
            "sideways",
            "use-glyph-orientation",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    textOverflow: {
        css: "text-overflow",
        values: ["clip", "ellipsis"],
        methods: [],
        type: "string",
        support: [],
    },
    textRendering: {
        css: "text-rendering",
        values: [
            "auto",
            "optimizeSpeed",
            "optimizeLegibility",
            "geometricPrecision",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    textShadow: {
        css: "text-shadow",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    textSizeAdjust: {
        css: "text-size-adjust",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    textTransform: {
        css: "text-transform",
        values: [
            "none",
            "capitalize",
            "uppercase",
            "lowercase",
            "full-width",
            "full-size-kana",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    textUnderlineOffset: {
        css: "text-underline-offset",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    textUnderlinePosition: {
        css: "text-underline-position",
        values: ["auto", "under", "left", "right"],
        methods: [],
        type: "string",
        support: [],
    },
    top: {
        css: "top",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    touchAction: {
        css: "touch-action",
        values: [
            "auto",
            "none",
            "pan-x",
            "pan-y",
            "manipulation",
            "pinch-zoom",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    transform: {
        css: "transform",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    transformBox: {
        css: "transform-box",
        values: [
            "content-box",
            "border-box",
            "fill-box",
            "stroke-box",
            "view-box",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    transformOrigin: {
        css: "transform-origin",
        values: ["left", "center", "right", "top", "bottom"],
        methods: [],
        type: "string",
        support: [],
    },
    transformStyle: {
        css: "transform-style",
        values: ["flat", "preserve-3d"],
        methods: [],
        type: "string",
        support: [],
    },
    transition: {
        css: "transition",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    transitionDelay: {
        css: "transition-delay",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    transitionDuration: {
        css: "transition-duration",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    transitionProperty: {
        css: "transition-property",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    transitionTimingFunction: {
        css: "transition-timing-function",
        values: [
            "ease",
            "ease-in",
            "ease-out",
            "ease-in-out",
            "linear",
            "step-start",
            "step-end",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    translate: {
        css: "translate",
        values: ["none"],
        methods: [],
        type: "string",
        support: [],
    },
    unicodeBidi: {
        css: "unicode-bidi",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    userSelect: {
        css: "user-select",
        values: ["none", "auto", "text", "contain", "all"],
        methods: [],
        type: "string",
        support: [],
    },
    verticalAlign: {
        css: "vertical-align",
        values: [
            "baseline",
            "sub",
            "super",
            "text-top",
            "text-bottom",
            "middle",
            "top",
            "bottom",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    visibility: {
        css: "visibility",
        values: ["visible", "hidden", "collapse"],
        methods: [],
        type: "string",
        support: [],
    },
    whiteSpace: {
        css: "white-space",
        values: [
            "normal",
            "nowrap",
            "pre",
            "pre-wrap",
            "pre-line",
            "break-spaces",
        ],
        methods: [],
        type: "string",
        support: [],
    },
    width: {
        css: "width",
        values: ["max-content", "min-content", "auto"],
        methods: [],
        type: "string",
        support: [],
    },
    widows: {
        css: "widows",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    wordBreak: {
        css: "word-break",
        values: ["normal", "break-all", "keep-all", "break-word"],
        methods: [],
        type: "string",
        support: [],
    },
    wordSpacing: {
        css: "word-spacing",
        values: ["normal"],
        methods: [],
        type: "string",
        support: [],
    },
    wordWrap: {
        css: "word-wrap",
        values: ["normal", "break-word", "anywhere"],
        methods: [],
        type: "string",
        support: [],
    },
    writingMode: {
        css: "writing-mode",
        values: ["horizontal-tb", "vertical-rl", "vertical-lr"],
        methods: [],
        type: "string",
        support: [],
    },
    zIndex: {
        css: "z-index",
        values: ["auto"],
        methods: [],
        type: "string",
        support: [],
    },
    zoom: { css: "zoom", values: [], methods: [], type: "string", support: [] },
    webkitLineClamp: {
        css: "-webkit-line-clamp",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    webkitAppearance: {
        css: "-webkit-appearance",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    webkitTextEmphasis: {
        css: "-webkit-text-emphasis",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    webkitHyphens: {
        css: "-webkit-hyphens",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    mozAppearance: {
        css: "-moz-appearance",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    mozTabSize: {
        css: "-moz-tab-size",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    mozHyphens: {
        css: "-moz-hyphens",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    oTabSize: {
        css: "-o-tab-size",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
    msHyphens: {
        css: "-ms-hyphens",
        values: [],
        methods: [],
        type: "string",
        support: [],
    },
};

module.exports = { List, globalValues };
