module.exports = {
    accentHeight: {
        name: "accent-height",
        type: "normal",
        values: "string",
        docs: [
            "The accent-height attribute defines the distance from the origin to the top of accent characters, measured by a distance within the font coordinate system.",
            "@deprecated",
        ],
    },
    accumulate: {
        name: "accumulate",
        type: "normal",
        values: ["sum", "none"],
        els: ["animate", "animateColor", "animateMotion", "animateTransform"],
        docs: [
            "The accumulate attribute controls whether or not an animation is cumulative.",
        ],
    },
    additive: {
        name: "additive",
        type: "normal",
        values: ["sum", "replace"],
        els: ["animate", "animateColor", "animateMotion", "animateTransform"],
        docs: [
            "The additive attribute controls whether or not an animation is additive.",
        ],
    },
    alignmentBaseline: {
        name: "alignment-baseline",
        type: "normal",
        values: [
            "auto",
            "baseline",
            "before-edge",
            "text-before-edge",
            "middle",
            "central",
            "after-edge",
            "text-after-edge",
            "ideographic",
            "alphabetic",
            "hanging",
            "mathematical",
            "top",
            "center",
            "bottom",
        ],
        els: ["tspan", "tref", "altGlyph", "textPath"],
        docs: [
            ,
            "The alignment-baseline attribute specifies how an object is aligned with respect to its parent. This property specifies which baseline of this element is to be aligned with the corresponding baseline of the parent. For example, this allows alphabetic baselines in Roman text to stay aligned across font size changes. It defaults to the baseline with the same name as the computed value of the alignment-baseline property.",
        ],
    },
    alphabetic: {
        name: "alphabetic",
        type: "normal",
        values: "string",
        els: ["font-face"],
        docs: [
            "The alphabetic attribute defines the lower baseline of a font. It has the same syntax and semantics as the baseline descriptor within an @font-face.",
            "@deprecated",
        ],
    },
    amplitude: {
        name: "amplitude",
        type: "number",
        values: [1],
        els: ["feFuncA", "feFuncB", "feFuncG", "feFuncR"],
        docs: [
            "The amplitude attribute controls the amplitude of the gamma function of a component transfer element when its type attribute is gamma.",
        ],
    },
    arabicForm: {
        name: "arabic-form",
        type: "normal",
        values: "string",
        els: ["glyph"],
        docs: [
            "The arabic-form attribute indicates which of the four possible forms an Arabic glyph represents.",
            "@deprecated",
        ],
    },
    ascent: {
        name: "ascent",
        type: "normal",
        values: "string",
        els: ["font-face"],
        docs: [
            "The ascent attribute defines the maximum unaccented height of the font within the font coordinate system.",
            "@deprecated",
        ],
    },
    attributeName: {
        name: "attributeName",
        type: "normal",
        values: "string",
        els: ["animate", "animateColor", "animateTransform", "set"],
        docs: [
            "The attributeName attribute indicates the name of the CSS property or attribute of the target element that is going to be changed during an animation.",
        ],
    },
    attributeType: {
        name: "attributeType",
        type: "normal",
        values: "string",
        els: ["animate", "animateColor", "animateTransform", "set"],
        docs: [
            "The attributeType attribute specifies the namespace in which the target attribute and its associated values are defined.",
            "@deprecated",
        ],
    },
    azimuth: {
        name: "azimuth",
        type: "normal",
        values: "number",
        els: ["feDistantLight"],
        docs: [
            "The azimuth attribute specifies the direction angle for the light source on the XY plane (clockwise), in degrees from the x axis.",
        ],
    },
    baseFrequency: {
        name: "baseFrequency",
        type: "normal",
        values: "string",
        els: ["feTurbulence"],
        docs: [
            "The baseFrequency attribute represents the base frequency parameter for the noise function of the ``<feTurbulence>`` filter primitive.",
        ],
    },
    baselineShift: {
        name: "baseline-shift",
        type: "normal",
        values: ["sub", "super"],
        els: ["altGlyph", "textPath", "tref", "tspan"],
        docs: [
            "The baseline-shift attribute allows repositioning of the dominant-baseline relative to the dominant-baseline of the parent text content element. The shifted object might be a sub- or superscript.",
        ],
    },
    baseProfile: {
        name: "baseProfile",
        type: "normal",
        values: "string",
        els: ["svg"],
        docs: [
            "The baseProfile attribute describes the minimum SVG language profile that the author believes is necessary to correctly render the content. The attribute does not specify any processing restrictions; It can be considered metadata.",
            "@deprecated",
        ],
    },
    bbox: {
        name: "bbox",
        type: "normal",
        values: "string",
        els: ["font-face"],
        docs: [
            "The bbox attribute defines the maximal bounding box of a font.",
            "@deprecated",
        ],
    },
    begin: {
        name: "begin",
        type: "normal",
        values: "string",
        els: [
            "animate",
            "animateColor",
            "animateMotion",
            "animateTransform",
            "discard",
            "set",
        ],
        docs: [
            "The begin attribute defines when an animation should begin or when an element should be discarded.",
        ],
    },
    bias: {
        name: "bias",
        type: "normal",
        values: "string",
        els: ["feConvolveMatrix"],
        docs: [
            "The bias attribute shifts the range of the filter. After applying the kernelMatrix of the ``<feConvolveMatrix>`` element to the input image to yield a number and applied the divisor attribute, the bias attribute is added to each component. This allows representation of values that would otherwise be clamped to 0 or 1.",
        ],
    },
    by: {
        name: "by",
        type: "normal",
        values: "string",
        els: ["animate", "animateColor", "animateMotion", "animateTransform"],
        docs: [
            "The by attribute specifies a relative offset value for an attribute that will be modified during an animation.",
        ],
    },
    calcMode: {
        name: "calcMode",
        type: "normal",
        values: "string",
        docs: [
            "The calcMode attribute specifies the interpolation mode for the animation.",
        ],
    },
    capHeight: {
        name: "cap-height",
        type: "normal",
        values: ["discrete", "linear", "paced", "spline"],
        els: ["animate", "animateColor", "animateMotion", "animateTransform"],
        docs: [
            "The cap-height attribute defines the height of uppercase glyphs of the font within the font coordinate system.",
            "@deprecated",
        ],
    },
    className: {
        name: "class",
        type: "normal",
        values: "string",
        els: true,
        docs: ["Often used with CSS to style elements with common properties."],
    },
    clip: {
        name: "clip",
        type: "normal",
        values: "string",
        els: ["font-face"],
        docs: [
            "The clip attribute is a presentation attribute defining the visible region of an element.",
            "@deprecated",
        ],
    },
    clipPathUnits: {
        name: "clipPathUnits",
        type: "normal",
        values: ["userSpaceOnUse", "objectBoundingBox"],
        els: ["clipPath"],
        docs: [
            "The clipPathUnits attribute indicates which coordinate system to use for the contents of the ``<clipPath>`` element.",
        ],
    },
    clipPath: {
        name: "clip-path",
        type: "normal",
        values: "string",
        els: [
            "a",
            "circle",
            "clipPath",
            "ellipse",
            "g",
            "glyph",
            "image",
            "line",
            "marker",
            "mask",
            "path",
            "pattern",
            "polygon",
            "polyline",
            "rect",
            "svg",
            "symbol",
            "text",
            "use",
        ],
        docs: [
            "The clip-path presentation attribute defines or associates a clipping path with the element it is related to.",
        ],
    },
    clipRule: {
        name: "clip-rule",
        type: "normal",
        values: ["nonzero", "evenodd"],
        els: [],
        docs: [
            "The clip-rule attribute only applies to graphics elements that are contained within a ``<clipPath>`` element. The clip-rule attribute basically works as the fill-rule attribute, except that it applies to ``<clipPath>`` definitions.",
        ],
    },
    color: {
        name: "color",
        type: "normal",
        values: "Color",
        els: [],
        docs: [
            "The color attribute is used to provide a potential indirect value, currentcolor, for the fill, stroke, stop-color, flood-color, and lighting-color attributes.",
        ],
    },
    colorInterpolation: {
        name: "color-interpolation",
        type: "normal",
        values: "string",
        docs: [
            "The color-interpolation attribute specifies the color space for gradient interpolations, color animations, and alpha compositing.",
        ],
    },
    colorInterpolationFilters: {
        name: "color-interpolation-filters",
        type: "normal",
        values: "string",
        docs: [
            "The color-interpolation-filters attribute specifies the color space for imaging operations performed via filter effects.",
        ],
    },
    colorProfile: {
        name: "color-profile",
        type: "normal",
        values: "string",
        docs: [
            "The color-profile attribute is used to define which color profile a raster image included through the ``<image>`` element should use.",
        ],
    },
    colorRendering: {
        name: "color-rendering",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    contentScriptType: {
        name: "contentScriptType",
        type: "normal",
        values: "string",
        docs: [
            "The contentScriptType attribute specifies the default scripting language for the given document fragment on the ``<svg>`` element.",
        ],
    },
    contentStyleType: {
        name: "contentStyleType",
        type: "normal",
        values: "string",
        docs: [
            "The contentStyleType attribute specifies the style sheet language for the given document fragment on the ``<svg>`` element.",
            "@deprecated",
        ],
    },
    crossorigin: {
        name: "crossorigin",
        type: "normal",
        values: "string",
        docs: [
            "The crossorigin attribute, valid on the ``<image>`` element, provides support for CORS, defining how the element handles crossorigin requests, thereby enabling the configuration of the CORS requests for the element's fetched data. It is a CORS settings attribute.",
        ],
    },
    cursor: {
        name: "cursor",
        type: "normal",
        values: "string",
        docs: [
            "The cursor attribute specifies the mouse cursor displayed when the mouse pointer is over an element.",
        ],
    },
    cx: {
        name: "cx",
        type: "normal",
        values: "string",
        docs: [
            "The cx attribute define the x-axis coordinate of a center point.",
        ],
    },
    cy: {
        name: "cy",
        type: "normal",
        values: "string",
        docs: [
            "The cy attribute define the y-axis coordinate of a center point.",
        ],
    },
    d: {
        name: "d",
        type: "normal",
        values: "string",
        els: [],
        docs: ["The d attribute defines a path to be drawn."],
    },
    decelerate: {
        name: "decelerate",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    descent: {
        name: "descent",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The descent attribute defines the maximum unaccented depth of the font.",
            "@deprecated",
        ],
    },
    diffuseConstant: {
        name: "diffuseConstant",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The diffuseConstant attribute represents the kd value in the Phong lighting model. In SVG, this can be any non-negative number.",
        ],
    },
    direction: {
        name: "direction",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The direction attribute specifies the inline-base direction of a ``<text>`` or ``<tspan>`` element. It defines the start and end points of a line of text as used by the text-anchor and inline-size properties. It also may affect the direction in which characters are positioned if the unicode-bidi property's value is either embed or bidi-override.",
        ],
    },
    display: {
        name: "display",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The display attribute lets you control the rendering of graphical or container elements.",
        ],
    },
    divisor: {
        name: "divisor",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The divisor attribute specifies the value by which the resulting number of applying the kernelMatrix of a ``<feConvolveMatrix>`` element to the input image color value is divided to yield the destination color value.",
        ],
    },
    dominantBaseline: {
        name: "dominant-baseline",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The dominant-baseline attribute specifies the dominant baseline, which is the baseline used to align the box's text and inline-level contents. It also indicates the default alignment baseline of any boxes participating in baseline alignment in the box's alignment context.",
        ],
    },
    dur: {
        name: "dur",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The dur attribute indicates the simple duration of an animation.",
        ],
    },
    dx: {
        name: "dx",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The dx attribute indicates a shift along the x-axis on the position of an element or its content.",
        ],
    },
    dy: {
        name: "dy",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The dy attribute indicates a shift along the y-axis on the position of an element or its content.",
        ],
    },
    edgeMode: {
        name: "edgeMode",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The edgeMode attribute determines how to extend the input image as necessary with color values so that the matrix operations can be applied when the kernel is positioned at or near the edge of the input image.",
        ],
    },
    elevation: {
        name: "elevation",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The elevation attribute specifies the direction angle for the light source from the XY plane towards the Z-axis, in degrees. Note that the positive Z-axis points towards the viewer of the content.",
        ],
    },
    enableBackground: {
        name: "enable-background",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The enable-background attribute specifies how the accumulation of the background image is managed.",
            "@deprecated",
        ],
    },
    end: {
        name: "end",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The end attribute defines an end value for the animation that can constrain the active duration.",
        ],
    },
    exponent: {
        name: "exponent",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The exponent attribute defines the exponent of the gamma function.",
        ],
    },
    fill: {
        name: "fill",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The fill attribute has two different meanings. For shapes and text it's a presentation attribute that defines the color (or any SVG paint servers like gradients or patterns) used to paint the element; for animation it defines the final state of the animation.",
        ],
    },
    fillOpacity: {
        name: "fill-opacity",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The fill-opacity attribute is a presentation attribute defining the opacity of the paint server (color, gradient, pattern, etc.) applied to a shape.",
        ],
    },
    fillRule: {
        name: "fill-rule",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The fill-rule attribute is a presentation attribute defining the algorithm to use to determine the inside part of a shape.",
        ],
    },
    filter: {
        name: "filter",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The filter attribute specifies the filter effects defined by the ``<filter>`` element that shall be applied to its element.",
        ],
    },
    filterRes: {
        name: "filterRes",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The filterRes attribute indicates the width and height of the intermediate images in pixels of a filter primitive.",
            "@deprecated",
        ],
    },
    filterUnits: {
        name: "filterUnits",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The filterUnits attribute defines the coordinate system for the attributes x, y, width and height.",
        ],
    },
    floodColor: {
        name: "flood-color",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The flood-color attribute indicates what color to use to flood the current filter primitive subregion.",
        ],
    },
    floodOpacity: {
        name: "flood-opacity",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The flood-opacity attribute indicates the opacity value to use across the current filter primitive subregion.",
        ],
    },
    fontFamily: {
        name: "font-family",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The font-family attribute indicates which font family will be used to render the text, specified as a prioritized list of font family names and/or generic family names.",
        ],
    },
    fontSize: {
        name: "font-size",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The font-size attribute refers to the size of the font from baseline to baseline when multiple lines of text are set solid in a multiline layout environment.",
        ],
    },
    fontSizeAdjust: {
        name: "font-size-adjust",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The font-size-adjust attribute allows authors to specify an aspect value for an element that will preserve the x-height of the first choice font in a substitute font.",
        ],
    },
    fontStretch: {
        name: "font-stretch",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The font-stretch attribute indicates the desired amount of condensing or expansion in the glyphs used to render the text.",
        ],
    },
    fontStyle: {
        name: "font-style",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The font-style attribute specifies whether the text is to be rendered using a normal, italic, or oblique face.",
        ],
    },
    fontVariant: {
        name: "font-variant",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The font-variant attribute indicates whether the text is to be rendered using variations of the font's glyphs.",
        ],
    },
    fontWeight: {
        name: "font-weight",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The font-weight attribute refers to the boldness or lightness of the glyphs used to render the text, relative to other fonts in the same font family.",
        ],
    },
    format: {
        name: "format",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The format attribute indicates the format of the given font.",
            "@deprecated",
        ],
    },
    from: {
        name: "from",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The from attribute indicates the initial value of the attribute that will be modified during the animation.",
        ],
    },
    fr: {
        name: "fr",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The fr attribute defines the radius of the focal point for the radial gradient.",
        ],
    },
    fx: {
        name: "fx",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The fx attribute defines the x-axis coordinate of the focal point for a radial gradient.",
        ],
    },
    fy: {
        name: "fy",
        type: "normal",
        values: "string",
        els: [],
        docs: [
            "The fy attribute defines the y-axis coordinate of the focal point for a radial gradient.",
        ],
    },
    g1: { name: "g1", type: "normal", values: "string", els: [], docs: [] },
    g2: { name: "g2", type: "normal", values: "string", els: [], docs: [] },
    glyphName: {
        name: "glyph-name",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    glyphOrientationHorizontal: {
        name: "glyph-orientation-horizontal",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    glyphOrientationVertical: {
        name: "glyph-orientation-vertical",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    glyphRef: {
        name: "glyphRef",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    gradientTransform: {
        name: "gradientTransform",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    gradientUnits: {
        name: "gradientUnits",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    hanging: {
        name: "hanging",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    height: {
        name: "height",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    href: { name: "href", type: "normal", values: "string", els: [], docs: [] },
    hreflang: {
        name: "hreflang",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    horizAdvX: {
        name: "horiz-adv-x",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    horizOriginX: {
        name: "horiz-origin-x",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    id: { name: "id", type: "normal", values: "string", els: [], docs: [] },
    ideographic: {
        name: "ideographic",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    imageRendering: {
        name: "image-rendering",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    in: { name: "in", type: "normal", values: "string", els: [], docs: [] },
    in2: { name: "in2", type: "normal", values: "string", els: [], docs: [] },
    intercept: {
        name: "intercept",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    k: { name: "k", type: "normal", values: "string", els: [], docs: [] },
    k1: { name: "k1", type: "normal", values: "string", els: [], docs: [] },
    k2: { name: "k2", type: "normal", values: "string", els: [], docs: [] },
    k3: { name: "k3", type: "normal", values: "string", els: [], docs: [] },
    k4: { name: "k4", type: "normal", values: "string", els: [], docs: [] },
    kernelMatrix: {
        name: "kernelMatrix",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    kernelUnitLength: {
        name: "kernelUnitLength",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    kerning: {
        name: "kerning",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    keyPoints: {
        name: "keyPoints",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    keySplines: {
        name: "keySplines",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    keyTimes: {
        name: "keyTimes",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    lang: { name: "lang", type: "normal", values: "string", els: [], docs: [] },
    lengthAdjust: {
        name: "lengthAdjust",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    letterSpacing: {
        name: "letter-spacing",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    lightingColor: {
        name: "lighting-color",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    limitingConeAngle: {
        name: "limitingConeAngle",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    local: {
        name: "local",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    markerEnd: {
        name: "marker-end",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    markerMid: {
        name: "marker-mid",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    markerStart: {
        name: "marker-start",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    markerHeight: {
        name: "markerHeight",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    markerUnits: {
        name: "markerUnits",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    markerWidth: {
        name: "markerWidth",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    mask: { name: "mask", type: "normal", values: "string", els: [], docs: [] },
    maskContentUnits: {
        name: "maskContentUnits",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    maskUnits: {
        name: "maskUnits",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    mathematical: {
        name: "mathematical",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    max: { name: "max", type: "normal", values: "string", els: [], docs: [] },
    media: {
        name: "media",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    method: {
        name: "method",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    min: { name: "min", type: "normal", values: "string", els: [], docs: [] },
    mode: { name: "mode", type: "normal", values: "string", els: [], docs: [] },
    name: { name: "name", type: "normal", values: "string", els: [], docs: [] },
    numOctaves: {
        name: "numOctaves",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    offset: {
        name: "offset",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    opacity: {
        name: "opacity",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    operator: {
        name: "operator",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    order: {
        name: "order",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    orient: {
        name: "orient",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    orientation: {
        name: "orientation",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    origin: {
        name: "origin",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    overflow: {
        name: "overflow",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    overlinePosition: {
        name: "overline-position",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    overlineThickness: {
        name: "overline-thickness",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    panose1: {
        name: "panose-1",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    paintOrder: {
        name: "paint-order",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    path: { name: "path", type: "normal", values: "string", els: [], docs: [] },
    pathLength: {
        name: "pathLength",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    patternContentUnits: {
        name: "patternContentUnits",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    patternTransform: {
        name: "patternTransform",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    patternUnits: {
        name: "patternUnits",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    ping: { name: "ping", type: "normal", values: "string", els: [], docs: [] },
    pointerEvents: {
        name: "pointer-events",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    points: {
        name: "points",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    pointsAtX: {
        name: "pointsAtX",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    pointsAtY: {
        name: "pointsAtY",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    pointsAtZ: {
        name: "pointsAtZ",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    preserveAlpha: {
        name: "preserveAlpha",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    preserveAspectRatio: {
        name: "preserveAspectRatio",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    primitiveUnits: {
        name: "primitiveUnits",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    r: { name: "r", type: "normal", values: "string", els: [], docs: [] },
    radius: {
        name: "radius",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    referrerPolicy: {
        name: "referrerPolicy",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    refX: { name: "refX", type: "normal", values: "string", els: [], docs: [] },
    refY: { name: "refY", type: "normal", values: "string", els: [], docs: [] },
    rel: { name: "rel", type: "normal", values: "string", els: [], docs: [] },
    renderingIntent: {
        name: "rendering-intent",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    repeatCount: {
        name: "repeatCount",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    repeatDur: {
        name: "repeatDur",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    requiredExtensions: {
        name: "requiredExtensions",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    requiredFeatures: {
        name: "requiredFeatures",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    restart: {
        name: "restart",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    result: {
        name: "result",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    rotate: {
        name: "rotate",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    rx: { name: "rx", type: "normal", values: "string", els: [], docs: [] },
    ry: { name: "ry", type: "normal", values: "string", els: [], docs: [] },
    scale: {
        name: "scale",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    seed: { name: "seed", type: "normal", values: "string", els: [], docs: [] },
    shapeRendering: {
        name: "shape-rendering",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    slope: {
        name: "slope",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    spacing: {
        name: "spacing",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    specularConstant: {
        name: "specularConstant",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    specularExponent: {
        name: "specularExponent",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    speed: {
        name: "speed",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    spreadMethod: {
        name: "spreadMethod",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    startOffset: {
        name: "startOffset",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    stdDeviation: {
        name: "stdDeviation",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    stemh: {
        name: "stemh",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    stemv: {
        name: "stemv",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    stitchTiles: {
        name: "stitchTiles",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    stopColor: {
        name: "stop-color",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    stopOpacity: {
        name: "stop-opacity",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    strikethroughPosition: {
        name: "strikethrough-position",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    strikethroughThickness: {
        name: "strikethrough-thickness",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    string: {
        name: "string",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    stroke: {
        name: "stroke",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    strokeDasharray: {
        name: "stroke-dasharray",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    strokeDashoffset: {
        name: "stroke-dashoffset",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    strokeLinecap: {
        name: "stroke-linecap",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    strokeLinejoin: {
        name: "stroke-linejoin",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    strokeMiterlimit: {
        name: "stroke-miterlimit",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    strokeOpacity: {
        name: "stroke-opacity",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    strokeWidth: {
        name: "stroke-width",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    surfaceScale: {
        name: "surfaceScale",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    systemLanguage: {
        name: "systemLanguage",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    tabindex: {
        name: "tabindex",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    tableValues: {
        name: "tableValues",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    target: {
        name: "target",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    targetX: {
        name: "targetX",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    targetY: {
        name: "targetY",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    textAnchor: {
        name: "text-anchor",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    textDecoration: {
        name: "text-decoration",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    textRendering: {
        name: "text-rendering",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    textLength: {
        name: "textLength",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    to: { name: "to", type: "normal", values: "string", els: [], docs: [] },
    transform: {
        name: "transform",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    transformOrigin: {
        name: "transform-origin",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    type: { name: "type", type: "normal", values: "string", els: [], docs: [] },
    u1: { name: "u1", type: "normal", values: "string", els: [], docs: [] },
    u2: { name: "u2", type: "normal", values: "string", els: [], docs: [] },
    underlinePosition: {
        name: "underline-position",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    underlineThickness: {
        name: "underline-thickness",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    unicode: {
        name: "unicode",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    unicodeBidi: {
        name: "unicode-bidi",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    unicodeRange: {
        name: "unicode-range",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    unitsPerEm: {
        name: "units-per-em",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    vAlphabetic: {
        name: "v-alphabetic",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    vHanging: {
        name: "v-hanging",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    vIdeographic: {
        name: "v-ideographic",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    vMathematical: {
        name: "v-mathematical",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    values: {
        name: "values",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    vectorEffect: {
        name: "vector-effect",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    version: {
        name: "version",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    vertAdvY: {
        name: "vert-adv-y",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    vertOriginX: {
        name: "vert-origin-x",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    vertOriginY: {
        name: "vert-origin-y",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    viewBox: {
        name: "viewBox",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    viewTarget: {
        name: "viewTarget",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    visibility: {
        name: "visibility",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    width: {
        name: "width",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    widths: {
        name: "widths",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    wordSpacing: {
        name: "word-spacing",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    writingMode: {
        name: "writing-mode",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    x: { name: "x", type: "normal", values: "string", els: [], docs: [] },
    xHeight: {
        name: "x-height",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    x1: { name: "x1", type: "normal", values: "string", els: [], docs: [] },
    x2: { name: "x2", type: "normal", values: "string", els: [], docs: [] },
    xChannelSelector: {
        name: "xChannelSelector",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    xlinkActuate: {
        name: "xlink:actuate",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    xlinkArcrole: {
        name: "xlink:arcrole",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    xLinkHref: {
        name: "xlink:href",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    xlinkRole: {
        name: "xlink:role",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    xlinkShow: {
        name: "xlink:show",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    xlinkTitle: {
        name: "xlink:title",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    xlinkType: {
        name: "xlink:type",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    xmlBase: {
        name: "xml:base",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    xmlLang: {
        name: "xml:lang",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    xmlSpace: {
        name: "xml:space",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    y: { name: "y", type: "normal", values: "string", els: [], docs: [] },
    y1: { name: "y1", type: "normal", values: "string", els: [], docs: [] },
    y2: { name: "y2", type: "normal", values: "string", els: [], docs: [] },
    yChannelSelector: {
        name: "yChannelSelector",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    z: { name: "z", type: "normal", values: "string", els: [], docs: [] },
    zoomAndPan: {
        name: "zoomAndPan",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    autoReverse: {
        name: "autoReverse",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
    accelerate: {
        name: "accelerate",
        type: "normal",
        values: "string",
        els: [],
        docs: [],
    },
};
