module.exports = {
    accentHeight: {
        name: "accent-height",
        type: "normal",
        values: "string",
        docs: [],
    },
    accumulate: {
        name: "accumulate",
        type: "normal",
        values: "string",
        docs: [],
    },
    additive: { name: "additive", type: "normal", values: "string", docs: [] },
    alignmentBaseline: {
        name: "alignment-baseline",
        type: "normal",
        values: "string",
        docs: [],
    },
    alphabetic: {
        name: "alphabetic",
        type: "normal",
        values: "string",
        docs: [],
    },
    amplitude: {
        name: "amplitude",
        type: "normal",
        values: "string",
        docs: [],
    },
    arabicForm: {
        name: "arabic-form",
        type: "normal",
        values: "string",
        docs: [],
    },
    ascent: { name: "ascent", type: "normal", values: "string", docs: [] },
    attributeName: {
        name: "attributeName",
        type: "normal",
        values: "string",
        docs: [],
    },
    attributeType: {
        name: "attributeType",
        type: "normal",
        values: "string",
        docs: [],
    },
    azimuth: { name: "azimuth", type: "normal", values: "string", docs: [] },
    baseFrequency: {
        name: "baseFrequency",
        type: "normal",
        values: "string",
        docs: [],
    },
    baselineShift: {
        name: "baseline-shift",
        type: "normal",
        values: "string",
        docs: [],
    },
    baseProfile: {
        name: "baseProfile",
        type: "normal",
        values: "string",
        docs: [],
    },
    bbox: { name: "bbox", type: "normal", values: "string", docs: [] },
    begin: { name: "begin", type: "normal", values: "string", docs: [] },
    bias: { name: "bias", type: "normal", values: "string", docs: [] },
    by: { name: "by", type: "normal", values: "string", docs: [] },
    calcMode: { name: "calcMode", type: "normal", values: "string", docs: [] },
    capHeight: {
        name: "cap-height",
        type: "normal",
        values: "string",
        docs: [],
    },
    class: { name: "class", type: "normal", values: "string", docs: [] },
    clip: { name: "clip", type: "normal", values: "string", docs: [] },
    clipPathUnits: {
        name: "clipPathUnits",
        type: "normal",
        values: "string",
        docs: [],
    },
    clipPath: { name: "clip-path", type: "normal", values: "string", docs: [] },
    clipRule: { name: "clip-rule", type: "normal", values: "string", docs: [] },
    color: { name: "color", type: "normal", values: "string", docs: [] },
    colorInterpolation: {
        name: "color-interpolation",
        type: "normal",
        values: "string",
        docs: [],
    },
    colorInterpolationFilters: {
        name: "color-interpolation-filters",
        type: "normal",
        values: "string",
        docs: [],
    },
    colorProfile: {
        name: "color-profile",
        type: "normal",
        values: "string",
        docs: [],
    },
    colorRendering: {
        name: "color-rendering",
        type: "normal",
        values: "string",
        docs: [],
    },
    contentScriptType: {
        name: "contentScriptType",
        type: "normal",
        values: "string",
        docs: [],
    },
    contentStyleType: {
        name: "contentStyleType",
        type: "normal",
        values: "string",
        docs: [],
    },
    crossorigin: {
        name: "crossorigin",
        type: "normal",
        values: "string",
        docs: [],
    },
    cursor: { name: "cursor", type: "normal", values: "string", docs: [] },
    cx: { name: "cx", type: "normal", values: "string", docs: [] },
    cy: { name: "cy", type: "normal", values: "string", docs: [] },
    d: { name: "d", type: "normal", values: "string", docs: [] },
    decelerate: {
        name: "decelerate",
        type: "normal",
        values: "string",
        docs: [],
    },
    descent: { name: "descent", type: "normal", values: "string", docs: [] },
    diffuseConstant: {
        name: "diffuseConstant",
        type: "normal",
        values: "string",
        docs: [],
    },
    direction: {
        name: "direction",
        type: "normal",
        values: "string",
        docs: [],
    },
    display: { name: "display", type: "normal", values: "string", docs: [] },
    divisor: { name: "divisor", type: "normal", values: "string", docs: [] },
    dominantBaseline: {
        name: "dominant-baseline",
        type: "normal",
        values: "string",
        docs: [],
    },
    dur: { name: "dur", type: "normal", values: "string", docs: [] },
    dx: { name: "dx", type: "normal", values: "string", docs: [] },
    dy: { name: "dy", type: "normal", values: "string", docs: [] },
    edgeMode: { name: "edgeMode", type: "normal", values: "string", docs: [] },
    elevation: {
        name: "elevation",
        type: "normal",
        values: "string",
        docs: [],
    },
    enableBackground: {
        name: "enable-background",
        type: "normal",
        values: "string",
        docs: [],
    },
    end: { name: "end", type: "normal", values: "string", docs: [] },
    exponent: { name: "exponent", type: "normal", values: "string", docs: [] },
    fill: { name: "fill", type: "normal", values: "string", docs: [] },
    fillOpacity: {
        name: "fill-opacity",
        type: "normal",
        values: "string",
        docs: [],
    },
    fillRule: { name: "fill-rule", type: "normal", values: "string", docs: [] },
    filter: { name: "filter", type: "normal", values: "string", docs: [] },
    filterRes: {
        name: "filterRes",
        type: "normal",
        values: "string",
        docs: [],
    },
    filterUnits: {
        name: "filterUnits",
        type: "normal",
        values: "string",
        docs: [],
    },
    floodColor: {
        name: "flood-color",
        type: "normal",
        values: "string",
        docs: [],
    },
    floodOpacity: {
        name: "flood-opacity",
        type: "normal",
        values: "string",
        docs: [],
    },
    fontFamily: {
        name: "font-family",
        type: "normal",
        values: "string",
        docs: [],
    },
    fontSize: { name: "font-size", type: "normal", values: "string", docs: [] },
    fontSizeAdjust: {
        name: "font-size-adjust",
        type: "normal",
        values: "string",
        docs: [],
    },
    fontStretch: {
        name: "font-stretch",
        type: "normal",
        values: "string",
        docs: [],
    },
    fontStyle: {
        name: "font-style",
        type: "normal",
        values: "string",
        docs: [],
    },
    fontVariant: {
        name: "font-variant",
        type: "normal",
        values: "string",
        docs: [],
    },
    fontWeight: {
        name: "font-weight",
        type: "normal",
        values: "string",
        docs: [],
    },
    format: { name: "format", type: "normal", values: "string", docs: [] },
    from: { name: "from", type: "normal", values: "string", docs: [] },
    fr: { name: "fr", type: "normal", values: "string", docs: [] },
    fx: { name: "fx", type: "normal", values: "string", docs: [] },
    fy: { name: "fy", type: "normal", values: "string", docs: [] },
    g1: { name: "g1", type: "normal", values: "string", docs: [] },
    g2: { name: "g2", type: "normal", values: "string", docs: [] },
    glyphName: {
        name: "glyph-name",
        type: "normal",
        values: "string",
        docs: [],
    },
    glyphOrientationHorizontal: {
        name: "glyph-orientation-horizontal",
        type: "normal",
        values: "string",
        docs: [],
    },
    glyphOrientationVertical: {
        name: "glyph-orientation-vertical",
        type: "normal",
        values: "string",
        docs: [],
    },
    glyphRef: { name: "glyphRef", type: "normal", values: "string", docs: [] },
    gradientTransform: {
        name: "gradientTransform",
        type: "normal",
        values: "string",
        docs: [],
    },
    gradientUnits: {
        name: "gradientUnits",
        type: "normal",
        values: "string",
        docs: [],
    },
    hanging: { name: "hanging", type: "normal", values: "string", docs: [] },
    height: { name: "height", type: "normal", values: "string", docs: [] },
    href: { name: "href", type: "normal", values: "string", docs: [] },
    hreflang: { name: "hreflang", type: "normal", values: "string", docs: [] },
    horizAdvX: {
        name: "horiz-adv-x",
        type: "normal",
        values: "string",
        docs: [],
    },
    horizOriginX: {
        name: "horiz-origin-x",
        type: "normal",
        values: "string",
        docs: [],
    },
    id: { name: "id", type: "normal", values: "string", docs: [] },
    ideographic: {
        name: "ideographic",
        type: "normal",
        values: "string",
        docs: [],
    },
    imageRendering: {
        name: "image-rendering",
        type: "normal",
        values: "string",
        docs: [],
    },
    in: { name: "in", type: "normal", values: "string", docs: [] },
    in2: { name: "in2", type: "normal", values: "string", docs: [] },
    intercept: {
        name: "intercept",
        type: "normal",
        values: "string",
        docs: [],
    },
    k: { name: "k", type: "normal", values: "string", docs: [] },
    k1: { name: "k1", type: "normal", values: "string", docs: [] },
    k2: { name: "k2", type: "normal", values: "string", docs: [] },
    k3: { name: "k3", type: "normal", values: "string", docs: [] },
    k4: { name: "k4", type: "normal", values: "string", docs: [] },
    kernelMatrix: {
        name: "kernelMatrix",
        type: "normal",
        values: "string",
        docs: [],
    },
    kernelUnitLength: {
        name: "kernelUnitLength",
        type: "normal",
        values: "string",
        docs: [],
    },
    kerning: { name: "kerning", type: "normal", values: "string", docs: [] },
    keyPoints: {
        name: "keyPoints",
        type: "normal",
        values: "string",
        docs: [],
    },
    keySplines: {
        name: "keySplines",
        type: "normal",
        values: "string",
        docs: [],
    },
    keyTimes: { name: "keyTimes", type: "normal", values: "string", docs: [] },
    lang: { name: "lang", type: "normal", values: "string", docs: [] },
    lengthAdjust: {
        name: "lengthAdjust",
        type: "normal",
        values: "string",
        docs: [],
    },
    letterSpacing: {
        name: "letter-spacing",
        type: "normal",
        values: "string",
        docs: [],
    },
    lightingColor: {
        name: "lighting-color",
        type: "normal",
        values: "string",
        docs: [],
    },
    limitingConeAngle: {
        name: "limitingConeAngle",
        type: "normal",
        values: "string",
        docs: [],
    },
    local: { name: "local", type: "normal", values: "string", docs: [] },
    markerEnd: {
        name: "marker-end",
        type: "normal",
        values: "string",
        docs: [],
    },
    markerMid: {
        name: "marker-mid",
        type: "normal",
        values: "string",
        docs: [],
    },
    markerStart: {
        name: "marker-start",
        type: "normal",
        values: "string",
        docs: [],
    },
    markerHeight: {
        name: "markerHeight",
        type: "normal",
        values: "string",
        docs: [],
    },
    markerUnits: {
        name: "markerUnits",
        type: "normal",
        values: "string",
        docs: [],
    },
    markerWidth: {
        name: "markerWidth",
        type: "normal",
        values: "string",
        docs: [],
    },
    mask: { name: "mask", type: "normal", values: "string", docs: [] },
    maskContentUnits: {
        name: "maskContentUnits",
        type: "normal",
        values: "string",
        docs: [],
    },
    maskUnits: {
        name: "maskUnits",
        type: "normal",
        values: "string",
        docs: [],
    },
    mathematical: {
        name: "mathematical",
        type: "normal",
        values: "string",
        docs: [],
    },
    max: { name: "max", type: "normal", values: "string", docs: [] },
    media: { name: "media", type: "normal", values: "string", docs: [] },
    method: { name: "method", type: "normal", values: "string", docs: [] },
    min: { name: "min", type: "normal", values: "string", docs: [] },
    mode: { name: "mode", type: "normal", values: "string", docs: [] },
    name: { name: "name", type: "normal", values: "string", docs: [] },
    numOctaves: {
        name: "numOctaves",
        type: "normal",
        values: "string",
        docs: [],
    },
    offset: { name: "offset", type: "normal", values: "string", docs: [] },
    opacity: { name: "opacity", type: "normal", values: "string", docs: [] },
    operator: { name: "operator", type: "normal", values: "string", docs: [] },
    order: { name: "order", type: "normal", values: "string", docs: [] },
    orient: { name: "orient", type: "normal", values: "string", docs: [] },
    orientation: {
        name: "orientation",
        type: "normal",
        values: "string",
        docs: [],
    },
    origin: { name: "origin", type: "normal", values: "string", docs: [] },
    overflow: { name: "overflow", type: "normal", values: "string", docs: [] },
    overlinePosition: {
        name: "overline-position",
        type: "normal",
        values: "string",
        docs: [],
    },
    overlineThickness: {
        name: "overline-thickness",
        type: "normal",
        values: "string",
        docs: [],
    },
    panose1: { name: "panose-1", type: "normal", values: "string", docs: [] },
    paintOrder: {
        name: "paint-order",
        type: "normal",
        values: "string",
        docs: [],
    },
    path: { name: "path", type: "normal", values: "string", docs: [] },
    pathLength: {
        name: "pathLength",
        type: "normal",
        values: "string",
        docs: [],
    },
    patternContentUnits: {
        name: "patternContentUnits",
        type: "normal",
        values: "string",
        docs: [],
    },
    patternTransform: {
        name: "patternTransform",
        type: "normal",
        values: "string",
        docs: [],
    },
    patternUnits: {
        name: "patternUnits",
        type: "normal",
        values: "string",
        docs: [],
    },
    ping: { name: "ping", type: "normal", values: "string", docs: [] },
    pointerEvents: {
        name: "pointer-events",
        type: "normal",
        values: "string",
        docs: [],
    },
    points: { name: "points", type: "normal", values: "string", docs: [] },
    pointsAtX: {
        name: "pointsAtX",
        type: "normal",
        values: "string",
        docs: [],
    },
    pointsAtY: {
        name: "pointsAtY",
        type: "normal",
        values: "string",
        docs: [],
    },
    pointsAtZ: {
        name: "pointsAtZ",
        type: "normal",
        values: "string",
        docs: [],
    },
    preserveAlpha: {
        name: "preserveAlpha",
        type: "normal",
        values: "string",
        docs: [],
    },
    preserveAspectRatio: {
        name: "preserveAspectRatio",
        type: "normal",
        values: "string",
        docs: [],
    },
    primitiveUnits: {
        name: "primitiveUnits",
        type: "normal",
        values: "string",
        docs: [],
    },
    r: { name: "r", type: "normal", values: "string", docs: [] },
    radius: { name: "radius", type: "normal", values: "string", docs: [] },
    referrerPolicy: {
        name: "referrerPolicy",
        type: "normal",
        values: "string",
        docs: [],
    },
    refX: { name: "refX", type: "normal", values: "string", docs: [] },
    refY: { name: "refY", type: "normal", values: "string", docs: [] },
    rel: { name: "rel", type: "normal", values: "string", docs: [] },
    renderingIntent: {
        name: "rendering-intent",
        type: "normal",
        values: "string",
        docs: [],
    },
    repeatCount: {
        name: "repeatCount",
        type: "normal",
        values: "string",
        docs: [],
    },
    repeatDur: {
        name: "repeatDur",
        type: "normal",
        values: "string",
        docs: [],
    },
    requiredExtensions: {
        name: "requiredExtensions",
        type: "normal",
        values: "string",
        docs: [],
    },
    requiredFeatures: {
        name: "requiredFeatures",
        type: "normal",
        values: "string",
        docs: [],
    },
    restart: { name: "restart", type: "normal", values: "string", docs: [] },
    result: { name: "result", type: "normal", values: "string", docs: [] },
    rotate: { name: "rotate", type: "normal", values: "string", docs: [] },
    rx: { name: "rx", type: "normal", values: "string", docs: [] },
    ry: { name: "ry", type: "normal", values: "string", docs: [] },
    scale: { name: "scale", type: "normal", values: "string", docs: [] },
    seed: { name: "seed", type: "normal", values: "string", docs: [] },
    shapeRendering: {
        name: "shape-rendering",
        type: "normal",
        values: "string",
        docs: [],
    },
    slope: { name: "slope", type: "normal", values: "string", docs: [] },
    spacing: { name: "spacing", type: "normal", values: "string", docs: [] },
    specularConstant: {
        name: "specularConstant",
        type: "normal",
        values: "string",
        docs: [],
    },
    specularExponent: {
        name: "specularExponent",
        type: "normal",
        values: "string",
        docs: [],
    },
    speed: { name: "speed", type: "normal", values: "string", docs: [] },
    spreadMethod: {
        name: "spreadMethod",
        type: "normal",
        values: "string",
        docs: [],
    },
    startOffset: {
        name: "startOffset",
        type: "normal",
        values: "string",
        docs: [],
    },
    stdDeviation: {
        name: "stdDeviation",
        type: "normal",
        values: "string",
        docs: [],
    },
    stemh: { name: "stemh", type: "normal", values: "string", docs: [] },
    stemv: { name: "stemv", type: "normal", values: "string", docs: [] },
    stitchTiles: {
        name: "stitchTiles",
        type: "normal",
        values: "string",
        docs: [],
    },
    stopColor: {
        name: "stop-color",
        type: "normal",
        values: "string",
        docs: [],
    },
    stopOpacity: {
        name: "stop-opacity",
        type: "normal",
        values: "string",
        docs: [],
    },
    strikethroughPosition: {
        name: "strikethrough-position",
        type: "normal",
        values: "string",
        docs: [],
    },
    strikethroughThickness: {
        name: "strikethrough-thickness",
        type: "normal",
        values: "string",
        docs: [],
    },
    string: { name: "string", type: "normal", values: "string", docs: [] },
    stroke: { name: "stroke", type: "normal", values: "string", docs: [] },
    strokeDasharray: {
        name: "stroke-dasharray",
        type: "normal",
        values: "string",
        docs: [],
    },
    strokeDashoffset: {
        name: "stroke-dashoffset",
        type: "normal",
        values: "string",
        docs: [],
    },
    strokeLinecap: {
        name: "stroke-linecap",
        type: "normal",
        values: "string",
        docs: [],
    },
    strokeLinejoin: {
        name: "stroke-linejoin",
        type: "normal",
        values: "string",
        docs: [],
    },
    strokeMiterlimit: {
        name: "stroke-miterlimit",
        type: "normal",
        values: "string",
        docs: [],
    },
    strokeOpacity: {
        name: "stroke-opacity",
        type: "normal",
        values: "string",
        docs: [],
    },
    strokeWidth: {
        name: "stroke-width",
        type: "normal",
        values: "string",
        docs: [],
    },
    surfaceScale: {
        name: "surfaceScale",
        type: "normal",
        values: "string",
        docs: [],
    },
    systemLanguage: {
        name: "systemLanguage",
        type: "normal",
        values: "string",
        docs: [],
    },
    tabindex: { name: "tabindex", type: "normal", values: "string", docs: [] },
    tableValues: {
        name: "tableValues",
        type: "normal",
        values: "string",
        docs: [],
    },
    target: { name: "target", type: "normal", values: "string", docs: [] },
    targetX: { name: "targetX", type: "normal", values: "string", docs: [] },
    targetY: { name: "targetY", type: "normal", values: "string", docs: [] },
    textAnchor: {
        name: "text-anchor",
        type: "normal",
        values: "string",
        docs: [],
    },
    textDecoration: {
        name: "text-decoration",
        type: "normal",
        values: "string",
        docs: [],
    },
    textRendering: {
        name: "text-rendering",
        type: "normal",
        values: "string",
        docs: [],
    },
    textLength: {
        name: "textLength",
        type: "normal",
        values: "string",
        docs: [],
    },
    to: { name: "to", type: "normal", values: "string", docs: [] },
    transform: {
        name: "transform",
        type: "normal",
        values: "string",
        docs: [],
    },
    transformOrigin: {
        name: "transform-origin",
        type: "normal",
        values: "string",
        docs: [],
    },
    type: { name: "type", type: "normal", values: "string", docs: [] },
    u1: { name: "u1", type: "normal", values: "string", docs: [] },
    u2: { name: "u2", type: "normal", values: "string", docs: [] },
    underlinePosition: {
        name: "underline-position",
        type: "normal",
        values: "string",
        docs: [],
    },
    underlineThickness: {
        name: "underline-thickness",
        type: "normal",
        values: "string",
        docs: [],
    },
    unicode: { name: "unicode", type: "normal", values: "string", docs: [] },
    unicodeBidi: {
        name: "unicode-bidi",
        type: "normal",
        values: "string",
        docs: [],
    },
    unicodeRange: {
        name: "unicode-range",
        type: "normal",
        values: "string",
        docs: [],
    },
    unitsPerEm: {
        name: "units-per-em",
        type: "normal",
        values: "string",
        docs: [],
    },
    vAlphabetic: {
        name: "v-alphabetic",
        type: "normal",
        values: "string",
        docs: [],
    },
    vHanging: { name: "v-hanging", type: "normal", values: "string", docs: [] },
    vIdeographic: {
        name: "v-ideographic",
        type: "normal",
        values: "string",
        docs: [],
    },
    vMathematical: {
        name: "v-mathematical",
        type: "normal",
        values: "string",
        docs: [],
    },
    values: { name: "values", type: "normal", values: "string", docs: [] },
    vectorEffect: {
        name: "vector-effect",
        type: "normal",
        values: "string",
        docs: [],
    },
    version: { name: "version", type: "normal", values: "string", docs: [] },
    vertAdvY: {
        name: "vert-adv-y",
        type: "normal",
        values: "string",
        docs: [],
    },
    vertOriginX: {
        name: "vert-origin-x",
        type: "normal",
        values: "string",
        docs: [],
    },
    vertOriginY: {
        name: "vert-origin-y",
        type: "normal",
        values: "string",
        docs: [],
    },
    viewBox: { name: "viewBox", type: "normal", values: "string", docs: [] },
    viewTarget: {
        name: "viewTarget",
        type: "normal",
        values: "string",
        docs: [],
    },
    visibility: {
        name: "visibility",
        type: "normal",
        values: "string",
        docs: [],
    },
    width: { name: "width", type: "normal", values: "string", docs: [] },
    widths: { name: "widths", type: "normal", values: "string", docs: [] },
    wordSpacing: {
        name: "word-spacing",
        type: "normal",
        values: "string",
        docs: [],
    },
    writingMode: {
        name: "writing-mode",
        type: "normal",
        values: "string",
        docs: [],
    },
    x: { name: "x", type: "normal", values: "string", docs: [] },
    xHeight: { name: "x-height", type: "normal", values: "string", docs: [] },
    x1: { name: "x1", type: "normal", values: "string", docs: [] },
    x2: { name: "x2", type: "normal", values: "string", docs: [] },
    xChannelSelector: {
        name: "xChannelSelector",
        type: "normal",
        values: "string",
        docs: [],
    },
    xlinkActuate: {
        name: "xlink:actuate",
        type: "normal",
        values: "string",
        docs: [],
    },
    xlinkArcrole: {
        name: "xlink:arcrole",
        type: "normal",
        values: "string",
        docs: [],
    },
    xlinkHref: {
        name: "xlink:href",
        type: "normal",
        values: "string",
        docs: [],
    },
    xlinkRole: {
        name: "xlink:role",
        type: "normal",
        values: "string",
        docs: [],
    },
    xlinkShow: {
        name: "xlink:show",
        type: "normal",
        values: "string",
        docs: [],
    },
    xlinkTitle: {
        name: "xlink:title",
        type: "normal",
        values: "string",
        docs: [],
    },
    xlinkType: {
        name: "xlink:type",
        type: "normal",
        values: "string",
        docs: [],
    },
    xmlBase: { name: "xml:base", type: "normal", values: "string", docs: [] },
    xmlLang: { name: "xml:lang", type: "normal", values: "string", docs: [] },
    xmlSpace: { name: "xml:space", type: "normal", values: "string", docs: [] },
    y: { name: "y", type: "normal", values: "string", docs: [] },
    y1: { name: "y1", type: "normal", values: "string", docs: [] },
    y2: { name: "y2", type: "normal", values: "string", docs: [] },
    yChannelSelector: {
        name: "yChannelSelector",
        type: "normal",
        values: "string",
        docs: [],
    },
    z: { name: "z", type: "normal", values: "string", docs: [] },
    zoomAndPan: {
        name: "zoomAndPan",
        type: "normal",
        values: "string",
        docs: [],
    },
    autoReverse: {
        name: "autoReverse",
        type: "normal",
        values: "string",
        docs: [],
    },
    accelerate: {
        name: "accelerate",
        type: "normal",
        values: "string",
        docs: [],
    },
};
