const { attribute } = require("../../templates");

/**
 * @credit MDN (2022) - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes
 */
module.exports = {
    ariaAutocomplete: attribute({
        name: "aria-autocomplete",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaChecked: attribute({
        name: "aria-checked",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaDisabled: attribute({
        name: "aria-disabled",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaErrormessage: attribute({
        name: "aria-errormessage",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaExpanded: attribute({
        name: "aria-expanded",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaHaspopup: attribute({
        name: "aria-haspopup",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaHidden: attribute({
        name: "aria-hidden",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaInvalid: attribute({
        name: "aria-invalid",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaLabel: attribute({
        name: "aria-label",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaLevel: attribute({
        name: "aria-level",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaModal: attribute({
        name: "aria-modal",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaMultiline: attribute({
        name: "aria-multiline",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaMultiselectable: attribute({
        name: "aria-multiselectable",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaOrientation: attribute({
        name: "aria-orientation",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaPlaceholder: attribute({
        name: "aria-placeholder",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaPressed: attribute({
        name: "aria-pressed",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaReadonly: attribute({
        name: "aria-readonly",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaRequired: attribute({
        name: "aria-required",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaSelected: attribute({
        name: "aria-selected",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaSort: attribute({
        name: "aria-sort",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaValuemax: attribute({
        name: "aria-valuemax",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaValuemin: attribute({
        name: "aria-valuemin",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaValuenow: attribute({
        name: "aria-valuenow",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaValuetext: attribute({
        name: "aria-valuetext",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaBusy: attribute({
        name: "aria-busy",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaLive: attribute({
        name: "aria-live",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaRelevant: attribute({
        name: "aria-relevant",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaAtomic: attribute({
        name: "aria-atomic",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaDropeffect: attribute({
        name: "aria-dropeffect",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaGrabbed: attribute({
        name: "aria-grabbed",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaActivedescendant: attribute({
        name: "aria-activedescendant",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaColcount: attribute({
        name: "aria-colcount",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaColindex: attribute({
        name: "aria-colindex",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaColspan: attribute({
        name: "aria-colspan",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaControls: attribute({
        name: "aria-controls",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaDescribedby: attribute({
        name: "aria-describedby",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaDescription: attribute({
        name: "aria-description",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaDetails: attribute({
        name: "aria-details",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaFlowto: attribute({
        name: "aria-flowto",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaLabelledby: attribute({
        name: "aria-labelledby",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaOwns: attribute({
        name: "aria-owns",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaPosinset: attribute({
        name: "aria-posinset",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaRowcount: attribute({
        name: "aria-rowcount",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaRowindex: attribute({
        name: "aria-rowindex",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaRowspan: attribute({
        name: "aria-rowspan",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaSetsize: attribute({
        name: "aria-setsize",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaCurrent: attribute({
        name: "aria-current",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaKeyshortcuts: attribute({
        name: "aria-keyshortcuts",
        values: "string",
        els: true,
        docs: [],
    }),
    ariaRoledescription: attribute({
        name: "aria-roledescription",
        values: "string",
        els: true,
        docs: [],
    }),
};
