module.exports = {
    ariaAutocomplete: {
        name: "aria-autocomplete",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaChecked: {
        name: "aria-checked",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaDisabled: {
        name: "aria-disabled",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaErrormessage: {
        name: "aria-errormessage",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaExpanded: {
        name: "aria-expanded",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaHaspopup: {
        name: "aria-haspopup",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaHidden: {
        name: "aria-hidden",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaInvalid: {
        name: "aria-invalid",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaLabel: {
        name: "aria-label",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaLevel: {
        name: "aria-level",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaModal: {
        name: "aria-modal",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaMultiline: {
        name: "aria-multiline",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaMultiselectable: {
        name: "aria-multiselectable",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaOrientation: {
        name: "aria-orientation",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaPlaceholder: {
        name: "aria-placeholder",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaPressed: {
        name: "aria-pressed",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaReadonly: {
        name: "aria-readonly",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaRequired: {
        name: "aria-required",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaSelected: {
        name: "aria-selected",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaSort: {
        name: "aria-sort",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaValuemax: {
        name: "aria-valuemax",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaValuemin: {
        name: "aria-valuemin",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaValuenow: {
        name: "aria-valuenow",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaValuetext: {
        name: "aria-valuetext",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaBusy: {
        name: "aria-busy",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaLive: {
        name: "aria-live",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaRelevant: {
        name: "aria-relevant",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaAtomic: {
        name: "aria-atomic",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaDropeffect: {
        name: "aria-dropeffect",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaGrabbed: {
        name: "aria-grabbed",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaActivedescendant: {
        name: "aria-activedescendant",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaColcount: {
        name: "aria-colcount",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaColindex: {
        name: "aria-colindex",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaColspan: {
        name: "aria-colspan",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaControls: {
        name: "aria-controls",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaDescribedby: {
        name: "aria-describedby",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaDescription: {
        name: "aria-description",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaDetails: {
        name: "aria-details",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaFlowto: {
        name: "aria-flowto",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaLabelledby: {
        name: "aria-labelledby",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaOwns: {
        name: "aria-owns",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaPosinset: {
        name: "aria-posinset",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaRowcount: {
        name: "aria-rowcount",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaRowindex: {
        name: "aria-rowindex",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaRowspan: {
        name: "aria-rowspan",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaSetsize: {
        name: "aria-setsize",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaCurrent: {
        name: "aria-current",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaKeyshortcuts: {
        name: "aria-keyshortcuts",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
    ariaRoledescription: {
        name: "aria-roledescription",
        type: "normal",
        values: "string",
        els: true,
        docs: [],
    },
};
